# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_element.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget, QInputDialog, QFileDialog
from PyQt5.QtGui import QPixmap


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(535, 276)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(350, 10, 151, 41))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_add_element = QtWidgets.QLabel(Dialog)
        self.label_add_element.setGeometry(QtCore.QRect(10, 20, 71, 16))
        self.label_add_element.setObjectName("label_add_element")
        self.lineEdit_filepath = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_filepath.setGeometry(QtCore.QRect(220, 20, 113, 20))
        self.lineEdit_filepath.setObjectName("lineEdit_filepath")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(110, 20, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.label_preview = QtWidgets.QLabel(Dialog)
        self.label_preview.setGeometry(QtCore.QRect(10, 60, 47, 13))
        self.label_preview.setObjectName("label_preview")
        self.label_image = QtWidgets.QLabel(Dialog)
        self.label_image.setGeometry(QtCore.QRect(10, 90, 511, 171))
        self.label_image.setText("")
        self.label_image.setObjectName("label_image")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        ####

        self.pushButton.clicked.connect(self.selectFile)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Select Skin Element"))
        self.label_add_element.setText(_translate("Dialog", "Add Element"))
        self.pushButton.setText(_translate("Dialog", "Select File"))
        self.label_preview.setText(_translate("Dialog", "Preview"))

    def openFileNameDialog(self):
        return(QFileDialog.getOpenFileName())

    def selectFile(self):
        file,_ = self.openFileNameDialog()
        print(file)
        self.label_image.setPixmap(QPixmap(file))
        self.lineEdit_filepath.setText(file)



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
