# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cursor_editor.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from PyQt5.QtGui import QPixmap
from PyQt5.QtWidgets import QWidget, QInputDialog, QFileDialog, QColorDialog
from PIL import Image, ImageDraw



class Ui_Dialog_cursor_editor(object):
    def setupUi(self, Dialog_cursor_editor):
        Dialog_cursor_editor.setObjectName("Dialog_cursor_editor")
        Dialog_cursor_editor.resize(485, 465)
        self.label_cursor_editor = QtWidgets.QLabel(Dialog_cursor_editor)
        self.label_cursor_editor.setGeometry(QtCore.QRect(20, 20, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_cursor_editor.setFont(font)
        self.label_cursor_editor.setObjectName("label_cursor_editor")
        self.label_preview = QtWidgets.QLabel(Dialog_cursor_editor)
        self.label_preview.setGeometry(QtCore.QRect(20, 60, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_preview.setFont(font)
        self.label_preview.setObjectName("label_preview")
        self.widget_preview = QtWidgets.QWidget(Dialog_cursor_editor)
        self.widget_preview.setGeometry(QtCore.QRect(20, 90, 131, 131))
        self.widget_preview.setObjectName("widget_preview")
        self.label_cursor_preview = QtWidgets.QLabel(self.widget_preview)
        self.label_cursor_preview.setGeometry(QtCore.QRect(0, 0, 131, 131))
        self.label_cursor_preview.setText("")
        self.label_cursor_preview.setObjectName("label_cursor_preview")
        self.label_elements = QtWidgets.QLabel(Dialog_cursor_editor)
        self.label_elements.setGeometry(QtCore.QRect(210, 60, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_elements.setFont(font)
        self.label_elements.setObjectName("label_elements")
        self.label_centre_circle = QtWidgets.QLabel(Dialog_cursor_editor)
        self.label_centre_circle.setGeometry(QtCore.QRect(210, 90, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_centre_circle.setFont(font)
        self.label_centre_circle.setObjectName("label_centre_circle")
        self.label_cc_radius = QtWidgets.QLabel(Dialog_cursor_editor)
        self.label_cc_radius.setGeometry(QtCore.QRect(210, 120, 51, 16))
        self.label_cc_radius.setObjectName("label_cc_radius")
        self.label_cc_color = QtWidgets.QLabel(Dialog_cursor_editor)
        self.label_cc_color.setGeometry(QtCore.QRect(210, 160, 47, 16))
        self.label_cc_color.setObjectName("label_cc_color")
        self.spinBox_cc_radius = QtWidgets.QSpinBox(Dialog_cursor_editor)
        self.spinBox_cc_radius.setGeometry(QtCore.QRect(260, 120, 42, 22))
        self.spinBox_cc_radius.setObjectName("spinBox_cc_radius")
        self.widget_cc_color_preview = QtWidgets.QWidget(Dialog_cursor_editor)
        self.widget_cc_color_preview.setGeometry(QtCore.QRect(310, 160, 21, 21))
        self.widget_cc_color_preview.setObjectName("widget_cc_color_preview")
        self.label_cc_color_preview = QtWidgets.QLabel(self.widget_cc_color_preview)
        self.label_cc_color_preview.setGeometry(QtCore.QRect(0, 0, 21, 21))
        self.label_cc_color_preview.setAutoFillBackground(False)
        self.label_cc_color_preview.setText("")
        self.label_cc_color_preview.setObjectName("label_cc_color_preview")
        self.pushButton_cc_color = QtWidgets.QPushButton(Dialog_cursor_editor)
        self.pushButton_cc_color.setGeometry(QtCore.QRect(330, 159, 75, 23))
        self.pushButton_cc_color.setObjectName("pushButton_cc_color")
        self.lineEdit_cc_color = QtWidgets.QLineEdit(Dialog_cursor_editor)
        self.lineEdit_cc_color.setGeometry(QtCore.QRect(250, 160, 61, 20))
        self.lineEdit_cc_color.setObjectName("lineEdit_cc_color")
        self.spinBox_oc_radius = QtWidgets.QSpinBox(Dialog_cursor_editor)
        self.spinBox_oc_radius.setGeometry(QtCore.QRect(260, 230, 42, 22))
        self.spinBox_oc_radius.setObjectName("spinBox_oc_radius")
        self.label_oc_color = QtWidgets.QLabel(Dialog_cursor_editor)
        self.label_oc_color.setGeometry(QtCore.QRect(210, 270, 47, 16))
        self.label_oc_color.setObjectName("label_oc_color")
        self.pushButton_oc_color = QtWidgets.QPushButton(Dialog_cursor_editor)
        self.pushButton_oc_color.setGeometry(QtCore.QRect(330, 269, 75, 23))
        self.pushButton_oc_color.setObjectName("pushButton_oc_color")
        self.widget_oc_color_preview = QtWidgets.QWidget(Dialog_cursor_editor)
        self.widget_oc_color_preview.setGeometry(QtCore.QRect(310, 270, 21, 21))
        self.widget_oc_color_preview.setObjectName("widget_oc_color_preview")
        self.label_oc_color_preview = QtWidgets.QLabel(self.widget_oc_color_preview)
        self.label_oc_color_preview.setGeometry(QtCore.QRect(0, 0, 21, 21))
        self.label_oc_color_preview.setAutoFillBackground(False)
        self.label_oc_color_preview.setText("")
        self.label_oc_color_preview.setObjectName("label_oc_color_preview")
        self.label_oc_radius = QtWidgets.QLabel(Dialog_cursor_editor)
        self.label_oc_radius.setGeometry(QtCore.QRect(210, 230, 51, 16))
        self.label_oc_radius.setObjectName("label_oc_radius")
        self.lineEdit_oc_color = QtWidgets.QLineEdit(Dialog_cursor_editor)
        self.lineEdit_oc_color.setGeometry(QtCore.QRect(250, 270, 61, 20))
        self.lineEdit_oc_color.setObjectName("lineEdit_oc_color")
        self.label_glow_radius = QtWidgets.QLabel(Dialog_cursor_editor)
        self.label_glow_radius.setGeometry(QtCore.QRect(211, 341, 51, 16))
        self.label_glow_radius.setObjectName("label_glow_radius")
        self.label_glow_color = QtWidgets.QLabel(Dialog_cursor_editor)
        self.label_glow_color.setGeometry(QtCore.QRect(211, 381, 47, 16))
        self.label_glow_color.setObjectName("label_glow_color")
        self.pushButton_glow_color = QtWidgets.QPushButton(Dialog_cursor_editor)
        self.pushButton_glow_color.setGeometry(QtCore.QRect(330, 379, 75, 23))
        self.pushButton_glow_color.setObjectName("pushButton_glow_color")
        self.spinBox_glow_radius = QtWidgets.QSpinBox(Dialog_cursor_editor)
        self.spinBox_glow_radius.setEnabled(True)
        self.spinBox_glow_radius.setGeometry(QtCore.QRect(261, 341, 42, 22))
        self.spinBox_glow_radius.setObjectName("spinBox_glow_radius")
        self.widget_glow_color_preview = QtWidgets.QWidget(Dialog_cursor_editor)
        self.widget_glow_color_preview.setGeometry(QtCore.QRect(310, 380, 21, 21))
        self.widget_glow_color_preview.setObjectName("widget_glow_colorpreview")
        self.label_glow_color_preview = QtWidgets.QLabel(self.widget_glow_color_preview)
        self.label_glow_color_preview.setGeometry(QtCore.QRect(0, 0, 21, 21))
        self.label_glow_color_preview.setAutoFillBackground(False)
        self.label_glow_color_preview.setText("")
        self.label_glow_color_preview.setObjectName("label_glow_color_preview")
        self.lineEdit_glow_color = QtWidgets.QLineEdit(Dialog_cursor_editor)
        self.lineEdit_glow_color.setEnabled(True)
        self.lineEdit_glow_color.setGeometry(QtCore.QRect(250, 380, 61, 20))
        self.lineEdit_glow_color.setObjectName("lineEdit_glow_color")
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_update_preview = QtWidgets.QPushButton(Dialog_cursor_editor)
        self.pushButton_update_preview.setGeometry(QtCore.QRect(90, 60, 75, 23))
        self.pushButton_update_preview.setObjectName("pushButton_update_preview")
        self.label_glow = QtWidgets.QLabel(Dialog_cursor_editor)
        self.label_glow.setGeometry(QtCore.QRect(210, 310, 47, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_glow.setFont(font)
        self.label_glow.setObjectName("label_glow")
        self.label_outer_circle = QtWidgets.QLabel(Dialog_cursor_editor)
        self.label_outer_circle.setGeometry(QtCore.QRect(210, 193, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_outer_circle.setFont(font)
        self.label_outer_circle.setObjectName("label_outer_circle")
        self.checkBox_antialiasing = QtWidgets.QCheckBox(Dialog_cursor_editor)
        self.checkBox_antialiasing.setGeometry(QtCore.QRect(20, 230, 111, 20))
        self.checkBox_antialiasing.setObjectName("checkBox_antialiasing")
        self.pushButton_confirm = QtWidgets.QPushButton(Dialog_cursor_editor)
        self.pushButton_confirm.setGeometry(QtCore.QRect(330, 430, 75, 23))
        self.pushButton_confirm.setObjectName("pushButton_confirm")

        self.retranslateUi(Dialog_cursor_editor)
        QtCore.QMetaObject.connectSlotsByName(Dialog_cursor_editor)

        #!---------------------------------------------------------------------!#

        self.initialisePreviews()
        self.pushButton_cc_color.clicked.connect(lambda: self.clickColorPicker(self.label_cc_color_preview, self.lineEdit_cc_color))
        self.pushButton_oc_color.clicked.connect(lambda: self.clickColorPicker(self.label_oc_color_preview, self.lineEdit_oc_color))
        self.pushButton_glow_color.clicked.connect(lambda: self.clickColorPicker(self.label_glow_color_preview, self.lineEdit_glow_color))
        self.pushButton_cc_color.clicked.connect(lambda: self.previewCursor())
        self.pushButton_oc_color.clicked.connect(lambda: self.previewCursor())
        self.pushButton_glow_color.clicked.connect(lambda: self.previewCursor())
        self.pushButton_update_preview.clicked.connect(lambda: self.previewCursor())
        self.spinBox_cc_radius.valueChanged.connect(lambda: self.previewCursor())
        self.spinBox_oc_radius.valueChanged.connect(lambda: self.previewCursor())
        self.spinBox_glow_radius.valueChanged.connect(lambda: self.previewCursor())
        self.checkBox_antialiasing.stateChanged.connect(lambda: self.previewCursor())
        self.pushButton_confirm.clicked.connect(lambda: self.accept())

    # from ui conversion
    def retranslateUi(self, Dialog_cursor_editor):
        _translate = QtCore.QCoreApplication.translate
        Dialog_cursor_editor.setWindowTitle(_translate("Dialog_cursor_editor", "Cursor Editor"))
        self.label_cursor_editor.setText(_translate("Dialog_cursor_editor", "Cursor Editor"))
        self.label_preview.setText(_translate("Dialog_cursor_editor", "Preview"))
        self.label_elements.setText(_translate("Dialog_cursor_editor", "Elements"))
        self.label_centre_circle.setText(_translate("Dialog_cursor_editor", "Centre Circle"))
        self.label_cc_radius.setText(_translate("Dialog_cursor_editor", "Radius"))
        self.label_cc_color.setText(_translate("Dialog_cursor_editor", "Color"))
        self.pushButton_cc_color.setText(_translate("Dialog_cursor_editor", "Select"))
        self.lineEdit_cc_color.setText(_translate("Dialog_cursor_editor", "#22FFFF"))
        self.label_oc_color.setText(_translate("Dialog_cursor_editor", "Color"))
        self.pushButton_oc_color.setText(_translate("Dialog_cursor_editor", "Select"))
        self.label_oc_radius.setText(_translate("Dialog_cursor_editor", "Radius"))
        self.lineEdit_oc_color.setText(_translate("Dialog_cursor_editor", "#AAFFFF"))
        self.label_glow_radius.setText(_translate("Dialog_cursor_editor", "Radius"))
        self.label_glow_color.setText(_translate("Dialog_cursor_editor", "Color"))
        self.pushButton_glow_color.setText(_translate("Dialog_cursor_editor", "Select"))
        self.lineEdit_glow_color.setText(_translate("Dialog_cursor_editor", "#121416"))
        self.pushButton_update_preview.setText(_translate("Dialog_cursor_editor", "Apply"))
        self.label_glow.setText(_translate("Dialog_cursor_editor", "Glow"))
        self.label_outer_circle.setText(_translate("Dialog_cursor_editor", "Outer Circle"))
        self.checkBox_antialiasing.setText(_translate("Dialog_cursor_editor", "Anti Aliasing"))
        self.pushButton_confirm.setText(_translate("Dialog_cursor_editor", "Accept"))

    def initialisePreviews(self):
        self.initialisePreview(self.label_cc_color_preview, self.lineEdit_cc_color)
        self.initialisePreview(self.label_oc_color_preview, self.lineEdit_oc_color)
        self.initialisePreview(self.label_glow_color_preview, self.lineEdit_glow_color)
        self.previewCursor()

    def initialisePreview(self, label, lineEdit):
        color=self.hex2rgb(lineEdit.text())
        preview_img = Image.new("RGB", (21,21), color=self.hex2rgb(lineEdit.text()))
        preview_img.save("preview.png")
        label.setPixmap(QPixmap("preview.png"))


    def hex2rgb(self, hex):
        #https://stackoverflow.com/questions/29643352/converting-hex-to-rgb-value-in-python
        h = hex.lstrip('#')
        return tuple(int(h[i:i+2], 16) for i in (0, 2, 4))


    def clickColorPicker(self, label, lineEdit):
        color = self.openColorDialog()
        lineEdit.setText(color.name())
        self.initialisePreview(label, lineEdit)

    def openColorDialog(self):
        return(QColorDialog.getColor())

    def previewCursor(self):
        size = (131,131)
        cursor_img = Image.new("RGB", size, color="white")
        cursor_draw = ImageDraw.Draw(cursor_img)
        centre_circle_radius = self.spinBox_cc_radius.value()
        outer_circle_radius = self.spinBox_oc_radius.value()
        # outer Circle
        cursor_draw.ellipse((size[0]/2+1-centre_circle_radius-outer_circle_radius,
                                size[1]/2+1-centre_circle_radius-outer_circle_radius,
                                size[0]/2+1+centre_circle_radius+outer_circle_radius,
                                size[1]/2+1+centre_circle_radius+outer_circle_radius),
                                fill=self.hex2rgb(self.lineEdit_oc_color.text()))
        print(centre_circle_radius, self.lineEdit_oc_color.text())
        # centre Circle

        cursor_draw.ellipse((size[0]/2+1-centre_circle_radius,
                                size[1]/2+1-centre_circle_radius,
                                size[0]/2+1+centre_circle_radius,
                                size[1]/2+1+centre_circle_radius),
                                fill=self.hex2rgb(self.lineEdit_cc_color.text()))
        print(centre_circle_radius, self.lineEdit_cc_color.text())

        if (self.checkBox_antialiasing.isChecked()):
            cursor_img = cursor_img.resize((size[0]*5,size[1]*5))
            cursor_img = cursor_img.resize((size[0],size[1]), Image.ANTIALIAS)
        cursor_img.save("cursor_preview.png")
        self.label_cursor_preview.setPixmap(QPixmap("cursor_preview.png"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_cursor_editor = QtWidgets.QDialog()
    ui = Ui_Dialog_cursor_editor()
    ui.setupUi(Dialog_cursor_editor)
    Dialog_cursor_editor.show()
    sys.exit(app.exec_())
