# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'element-browser.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(683, 605)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_element_browser = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_element_browser.sizePolicy().hasHeightForWidth())
        self.label_element_browser.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_element_browser.setFont(font)
        self.label_element_browser.setLineWidth(7)
        self.label_element_browser.setObjectName("label_element_browser")
        self.verticalLayout.addWidget(self.label_element_browser)
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 663, 560))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_element = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_element.sizePolicy().hasHeightForWidth())
        self.widget_element.setSizePolicy(sizePolicy)
        self.widget_element.setMinimumSize(QtCore.QSize(0, 150))
        self.widget_element.setObjectName("widget_element")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_element)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_image = QtWidgets.QLabel(self.widget_element)
        self.label_image.setMinimumSize(QtCore.QSize(0, 0))
        self.label_image.setMaximumSize(QtCore.QSize(235, 132))
        self.label_image.setObjectName("label_image")
        self.horizontalLayout.addWidget(self.label_image)
        self.label_skin_name = QtWidgets.QLabel(self.widget_element)
        self.label_skin_name.setObjectName("label_skin_name")
        self.horizontalLayout.addWidget(self.label_skin_name)
        self.pushButton_select = QtWidgets.QPushButton(self.widget_element)
        self.pushButton_select.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_select.setObjectName("pushButton_select")
        self.horizontalLayout.addWidget(self.pushButton_select)
        self.verticalLayout_2.addWidget(self.widget_element)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_element_browser.setText(_translate("Dialog", "Element Browser"))
        self.label_image.setText(_translate("Dialog", "[image]"))
        self.label_skin_name.setText(_translate("Dialog", "Skin Name"))
        self.pushButton_select.setText(_translate("Dialog", "Select"))
    


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
