# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'element-browser.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


from PyQt5.QtWidgets import QWidget, QInputDialog, QFileDialog, QDialog, QMessageBox
from PyQt5.QtGui import QPixmap
from PyQt5.QtCore import QTimer
import add_element_01
import cursor_editor_01

import json
import os
import shutil
from PIL import Image

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(683, 605)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_element_browser = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_element_browser.sizePolicy().hasHeightForWidth())
        self.label_element_browser.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_element_browser.setFont(font)
        self.label_element_browser.setLineWidth(7)
        self.label_element_browser.setObjectName("label_element_browser")
        self.verticalLayout.addWidget(self.label_element_browser)
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 663, 560))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        ######################

        self.containers = {}
        self.createElements()

        ##########################

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        ############

        QTimer.singleShot(1,self.postLoadFunctions)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_element_browser.setText(_translate("Dialog", "Element Browser"))

        ##############
        self.addUiText()

    def createElements(self):
        self.skin_folder = r'D:/osu!/Skins - Archive'
        self.element = 'ranking-panel'
        self.loading = 'loading.png'
        self.pre_load = False
        self.max_image_height = 132
        self.max_image_width = 235

        self.elements = {} # format {skin name : image object}
        skins = os.listdir(self.skin_folder)

        for skin in skins:

            self.containers[skin] = {}
            try:
                skin_dir = os.listdir("/".join([self.skin_folder,skin]))
            except:
                #print("".join([skin_folder,skin," is not a folder"]))
                pass
            else:
                if "".join([self.element, ".png"]) not in skin_dir and "".join([self.element, "@2x.png"]) in skin_dir:
                    img_loc = False
                elif "".join([self.element, "@2x.png"]) in skin_dir:
                    img_loc = "".join([self.skin_folder,"/",skin,"/",self.element,"@2x.png"])
                elif "".join([self.element, ".png"]) in skin_dir:
                    img_loc = "".join([self.skin_folder,"/",skin,"/",self.element,".png"])
                    # create elements
                if img_loc:
                    self.containers[skin]["widget_element"] = QtWidgets.QWidget(self.scrollAreaWidgetContents)
                    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
                    sizePolicy.setHorizontalStretch(0)
                    sizePolicy.setVerticalStretch(0)
                    sizePolicy.setHeightForWidth(self.containers[skin]["widget_element"].sizePolicy().hasHeightForWidth())
                    self.containers[skin]["widget_element"].setSizePolicy(sizePolicy)
                    self.containers[skin]["widget_element"].setMinimumSize(QtCore.QSize(0, 150))
                    self.containers[skin]["widget_element"].setObjectName("".join(["widget_element_",skin]))
                    self.containers[skin]["horizontalLayout"] = QtWidgets.QHBoxLayout(self.containers[skin]["widget_element"])
                    self.containers[skin]["horizontalLayout"].setObjectName("".join(["horizontalLayout",skin]))
                    self.containers[skin]["label_image"] = QtWidgets.QLabel(self.containers[skin]["widget_element"])
                    self.containers[skin]["label_image"].setMinimumSize(QtCore.QSize(0, 0))
                    self.containers[skin]["label_image"].setMaximumSize(QtCore.QSize(235, 132))
                    self.containers[skin]["label_image"].setObjectName("".join(["label_image",skin]))
                    self.containers[skin]["horizontalLayout"].addWidget(self.containers[skin]["label_image"])
                    self.containers[skin]["label_skin_name"] = QtWidgets.QLabel(self.containers[skin]["widget_element"])
                    self.containers[skin]["label_skin_name"].setObjectName("".join(["label_skin_name",skin]))
                    self.containers[skin]["horizontalLayout"].addWidget(self.containers[skin]["label_skin_name"])
                    self.containers[skin]["pushButton_select"] = QtWidgets.QPushButton(self.containers[skin]["widget_element"])
                    self.containers[skin]["pushButton_select"].setMaximumSize(QtCore.QSize(100, 16777215))
                    self.containers[skin]["pushButton_select"].setObjectName("".join(["pushButton_select",skin]))
                    self.containers[skin]["horizontalLayout"].addWidget(self.containers[skin]["pushButton_select"])
                    # set images

                    if self.pre_load:
                        try:
                            preview = Image.open(img_loc)#.resize((max_image_width, max_image_height), Image.ANTIALIAS)
                        except:
                            print("failed to open", preview)
                        else:
                            original_width, original_height = preview.size
                            width_ratio = original_width/max_image_width
                            height_ratio = original_height/max_image_height
                            if (width_ratio > height_ratio):
                                preview = preview.resize((max_image_width, int(original_height/width_ratio)), Image.ANTIALIAS)
                            elif (height_ratio > width_ratio):
                                preview = preview.resize((int(original_width/height_ratio), max_image_height), Image.ANTIALIAS)
                            else:
                                preview = preview.resize((max_image_width, max_image_height), Image.ANTIALIAS)
                            preview.save("element_preview.png")
                            self.containers[skin]["label_image"].setPixmap(QPixmap("element_preview.png"))

                    else:
                        self.containers[skin]["label_image"].setPixmap(QPixmap("loading.png"))
                    self.elements[skin] = img_loc

                    self.verticalLayout_2.addWidget(self.containers[skin]["widget_element"])

    def addUiText(self):
        for skin in self.containers:
            if "pushButton_select" in self.containers[skin].keys():
                self.containers[skin]["pushButton_select"].setText("Select")
                self.containers[skin]["label_skin_name"].setText(skin)

    def postLoadFunctions(self):
        print("a")
        self.postLoadPreviews()

    def postLoadPreviews(self):
        for skin in self.containers:
            if "label_image" in self.containers[skin].keys():
                try:
                    skin_dir = os.listdir("/".join([self.skin_folder,skin]))
                except:
                    #print("".join([skin_folder,skin," is not a folder"]))
                    pass
                else:
                    if "".join([self.element, ".png"]) not in skin_dir and "".join([self.element, "@2x.png"]) in skin_dir:
                        img_loc = False
                    elif "".join([self.element, "@2x.png"]) in skin_dir:
                        img_loc = "".join([self.skin_folder,"/",skin,"/",self.element,"@2x.png"])
                    elif "".join([self.element, ".png"]) in skin_dir:
                        img_loc = "".join([self.skin_folder,"/",skin,"/",self.element,".png"])

                if img_loc:
                    self.loadPreview(img_loc, self.containers[skin]["label_image"])


    def loadPreview(self, img_loc, label_image):
        try:
            preview = Image.open(img_loc)#.resize((max_image_width, max_image_height), Image.ANTIALIAS)
        except:
            print("failed to open", img_loc)
        else:
            original_width, original_height = preview.size
            width_ratio = original_width/self.max_image_width
            height_ratio = original_height/self.max_image_height
            if (width_ratio > height_ratio):
                preview = preview.resize((self.max_image_width, int(original_height/width_ratio)), Image.ANTIALIAS)
            elif (height_ratio > width_ratio):
                preview = preview.resize((int(original_width/height_ratio), self.max_image_height), Image.ANTIALIAS)
            else:
                preview = preview.resize((self.max_image_width, self.max_image_height), Image.ANTIALIAS)
            preview.save("element_preview.png")
            label_image.setPixmap(QPixmap("element_preview.png"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
