# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'osu_skin_helper.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget, QInputDialog, QFileDialog, QDialog, QMessageBox
from PyQt5.QtGui import QPixmap
import add_element_01
import cursor_editor_01

from threading import Thread
import json
import os
import shutil
from PIL import Image
import sys

class ElementBrowser(QWidget):

    #def __init__(self):
        #super().__init__()

        #self.createElements()


    def setupUi(self, Dialog, element):
        Dialog.setObjectName("Dialog")
        Dialog.resize(683, 605)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_element_browser = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_element_browser.sizePolicy().hasHeightForWidth())
        self.label_element_browser.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_element_browser.setFont(font)
        self.label_element_browser.setLineWidth(7)
        self.label_element_browser.setObjectName("label_element_browser")
        self.verticalLayout.addWidget(self.label_element_browser)
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 663, 560))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        ######################

        self.return_value = ""
        self.element = element
        self.containers = {}
        self.createElements(Dialog)

        ##########################

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        ############
        #QTimer.singleShot(1,self.postLoadFunctions)
        self.postLoadFunctions()

    def thread(self):
        t1=Thread(target=self.Operation)
        t1.start()

    def loadPreview(self, img_loc, label_image):
        try:
            preview = Image.open(img_loc)#.resize((max_image_width, max_image_height), Image.ANTIALIAS)
        except:
            print("failed to open", img_loc)
        else:
            self.max_image_height = 132
            self.max_image_width = 235
            original_width, original_height = preview.size
            width_ratio = original_width/self.max_image_width
            height_ratio = original_height/self.max_image_height
            if (width_ratio > height_ratio):
                preview = preview.resize((self.max_image_width, int(original_height/width_ratio)), Image.ANTIALIAS)
            elif (height_ratio > width_ratio):
                preview = preview.resize((int(original_width/height_ratio), self.max_image_height), Image.ANTIALIAS)
            else:
                preview = preview.resize((self.max_image_width, self.max_image_height), Image.ANTIALIAS)
            preview.save("element_preview.png")
            label_image.setPixmap(QPixmap("element_preview.png"))

    def createElements(self, Dialog):
        self.skin_folder = r'D:/osu!/Skins'
        #self.element = 'ranking-panel'
        self.loading = 'loading.png'
        self.pre_load = False
        self.max_image_height = 132
        self.max_image_width = 235

        self.elements = {} # format {skin name : image object}
        skins = os.listdir(self.skin_folder)

        for skin in skins:
            img_loc = False
            self.containers[skin] = {}
            try:
                skin_dir = os.listdir("/".join([self.skin_folder,skin]))
            except:
                #print("".join([skin_folder,skin," is not a folder"]))
                pass
            else:
                if "".join([self.element, ".png"]) not in skin_dir and "".join([self.element, "@2x.png"]) not in skin_dir:
                    if "".join([self.element, ".jpg"]) in skin_dir:  # catches menu-background.jpg
                        img_loc = "".join([self.skin_folder,"/",skin,"/",self.element,".jpg"])
                elif "".join([self.element, "@2x.png"]) in skin_dir:
                    img_loc = "".join([self.skin_folder,"/",skin,"/",self.element,"@2x.png"])
                elif "".join([self.element, ".png"]) in skin_dir:
                    img_loc = "".join([self.skin_folder,"/",skin,"/",self.element,".png"])
                    # create elements
                else:
                    print("img_loc not identified")
                    img_loc = False
                if img_loc:
                    self.containers[skin]["widget_element"] = QtWidgets.QWidget(self.scrollAreaWidgetContents)
                    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
                    sizePolicy.setHorizontalStretch(0)
                    sizePolicy.setVerticalStretch(0)
                    sizePolicy.setHeightForWidth(self.containers[skin]["widget_element"].sizePolicy().hasHeightForWidth())
                    self.containers[skin]["widget_element"].setSizePolicy(sizePolicy)
                    self.containers[skin]["widget_element"].setMinimumSize(QtCore.QSize(0, 150))
                    self.containers[skin]["widget_element"].setObjectName("".join(["widget_element_",skin]))
                    self.containers[skin]["horizontalLayout"] = QtWidgets.QHBoxLayout(self.containers[skin]["widget_element"])
                    self.containers[skin]["horizontalLayout"].setObjectName("".join(["horizontalLayout",skin]))
                    self.containers[skin]["label_image"] = QtWidgets.QLabel(self.containers[skin]["widget_element"])
                    self.containers[skin]["label_image"].setMinimumSize(QtCore.QSize(0, 0))
                    self.containers[skin]["label_image"].setMaximumSize(QtCore.QSize(235, 132))
                    self.containers[skin]["label_image"].setObjectName("".join(["label_image",skin]))
                    self.containers[skin]["horizontalLayout"].addWidget(self.containers[skin]["label_image"])
                    self.containers[skin]["label_skin_name"] = QtWidgets.QLabel(self.containers[skin]["widget_element"])
                    self.containers[skin]["label_skin_name"].setObjectName("".join(["label_skin_name",skin]))
                    self.containers[skin]["horizontalLayout"].addWidget(self.containers[skin]["label_skin_name"])
                    self.containers[skin]["pushButton_select"] = QtWidgets.QPushButton(self.containers[skin]["widget_element"])
                    self.containers[skin]["pushButton_select"].setMaximumSize(QtCore.QSize(100, 16777215))
                    self.containers[skin]["pushButton_select"].setObjectName("".join(["pushButton_select",skin]))
                    self.containers[skin]["horizontalLayout"].addWidget(self.containers[skin]["pushButton_select"])

                    self.containers[skin]["pushButton_select"].clicked.connect(lambda ignore, img_loc=img_loc: self.confirm(img_loc))
                    self.containers[skin]["pushButton_select"].clicked.connect(Dialog.close)

                    # set images

                    if self.pre_load:
                        try:
                            preview = Image.open(img_loc)#.resize((max_image_width, max_image_height), Image.ANTIALIAS)
                        except:
                            print("failed to open", preview)
                        else:
                            original_width, original_height = preview.size
                            width_ratio = original_width/max_image_width
                            height_ratio = original_height/max_image_height
                            if (width_ratio > height_ratio):
                                preview = preview.resize((max_image_width, int(original_height/width_ratio)), Image.ANTIALIAS)
                            elif (height_ratio > width_ratio):
                                preview = preview.resize((int(original_width/height_ratio), max_image_height), Image.ANTIALIAS)
                            else:
                                preview = preview.resize((max_image_width, max_image_height), Image.ANTIALIAS)
                            preview.save("element_preview.png")
                            self.containers[skin]["label_image"].setPixmap(QPixmap("element_preview.png"))

                    else:
                        self.containers[skin]["label_image"].setPixmap(QPixmap("loading.png"))
                        self.containers[skin]["img_loc"] = img_loc
                    self.elements[skin] = img_loc

                    self.verticalLayout_2.addWidget(self.containers[skin]["widget_element"])

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_element_browser.setText(_translate("Dialog", "Element Browser"))
        for skin in self.containers:
            if "pushButton_select" in self.containers[skin].keys():
                self.containers[skin]["pushButton_select"].setText("Select")
                self.containers[skin]["label_skin_name"].setText(skin)

    def postLoadFunctions(self):
        t1=Thread(target=self.Operation)
        t1.start()

    def Operation(self):
        print("Operation Start")
        for skin in self.containers:
            if "img_loc" in self.containers[skin].keys():
                self.loadPreview(self.containers[skin]["img_loc"], self.containers[skin]["label_image"])
        print("Operation Finish")

    def confirm(self, skin):
        print(skin)
        self.return_value = skin

class AddElement(QInputDialog):

    #dialog_return = QtCore.pyqtSignal(str)

    def setupUi(self, Dialog, element):
        Dialog.setObjectName("Dialog")
        Dialog.resize(678, 303)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_add_element = QtWidgets.QLabel(self.widget)
        self.label_add_element.setObjectName("label_add_element")
        self.horizontalLayout.addWidget(self.label_add_element)
        self.pushButton_element_browser = QtWidgets.QPushButton(self.widget)
        self.pushButton_element_browser.setObjectName("pushButton_element_browser")
        self.horizontalLayout.addWidget(self.pushButton_element_browser)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.lineEdit_filepath = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_filepath.setText("")
        self.lineEdit_filepath.setObjectName("lineEdit_filepath")
        self.horizontalLayout.addWidget(self.lineEdit_filepath)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.widget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.verticalLayout.addWidget(self.widget)
        self.label_preview = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_preview.sizePolicy().hasHeightForWidth())
        self.label_preview.setSizePolicy(sizePolicy)
        self.label_preview.setObjectName("label_preview")
        self.verticalLayout.addWidget(self.label_preview)
        self.label_image = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_image.sizePolicy().hasHeightForWidth())
        self.label_image.setSizePolicy(sizePolicy)
        self.label_image.setText("")
        self.label_image.setObjectName("label_image")
        self.verticalLayout.addWidget(self.label_image)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(self.confirm)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        ####

        self.element = element
        self.pushButton.clicked.connect(self.selectFile)
        self.pushButton_element_browser.clicked.connect(self.elementBrowser)


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Select Skin Element"))
        self.label_add_element.setText(_translate("Dialog", "Add Element"))
        self.pushButton.setText(_translate("Dialog", "Select File"))
        self.pushButton_element_browser.setText(_translate("Dialog", "Element Browser"))
        self.label_preview.setText(_translate("Dialog", "Preview"))


    def openFileNameDialog(self):
        return(QFileDialog.getOpenFileName())

    def selectFile(self):
        file,_ = self.openFileNameDialog()
        print(file)
        self.label_image.setPixmap(QPixmap(file))
        self.lineEdit_filepath.setText(file)

    def elementBrowser(self):
        print("elementBrowser")
        Dialog = QtWidgets.QDialog()
        ui_element_browser = ElementBrowser()
        ui_element_browser.setupUi(Dialog, self.element)
        Dialog.show()
        Dialog.exec_()
        print(ui_element_browser.return_value)
        file = ui_element_browser.return_value
        try:
            print("Element Browser: recieved", ui_element_browser.return_value)
            self.lineEdit_filepath.setText(ui_element_browser.return_value)
        except:
            print("failed to update")
        try:
            self.label_image.setPixmap(QPixmap(file))
            self.lineEdit_filepath.setText(file)
        except:
            print("file not image/ not found")


    def confirm(self):
        self.return_value = self.lineEdit_filepath.text()
        #self.dialog_return.emit(return_value)
"""
class EditIni(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(458, 465)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(0, 41))
        self.widget.setObjectName("widget")
        self.horizontalLayout_46 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.label_skin_ini_editor_header = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_skin_ini_editor_header.sizePolicy().hasHeightForWidth())
        self.label_skin_ini_editor_header.setSizePolicy(sizePolicy)
        self.label_skin_ini_editor_header.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_skin_ini_editor_header.setFont(font)
        self.label_skin_ini_editor_header.setObjectName("label_skin_ini_editor_header")
        self.horizontalLayout_46.addWidget(self.label_skin_ini_editor_header)
        self.pushButton_skin_ini_save = QtWidgets.QPushButton(self.widget)
        self.pushButton_skin_ini_save.setMaximumSize(QtCore.QSize(75, 16777215))
        self.pushButton_skin_ini_save.setObjectName("pushButton_skin_ini_save")
        self.horizontalLayout_46.addWidget(self.pushButton_skin_ini_save)
        self.verticalLayout.addWidget(self.widget)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_general = QtWidgets.QWidget()
        self.tab_general.setObjectName("tab_general")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab_general)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_general)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 414, 352))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_name = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_name.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_name.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widget_name.setObjectName("widget_name")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_name)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_name = QtWidgets.QLabel(self.widget_name)
        self.label_name.setObjectName("label_name")
        self.horizontalLayout_2.addWidget(self.label_name)
        self.lineEdit_name = QtWidgets.QLineEdit(self.widget_name)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_name.sizePolicy().hasHeightForWidth())
        self.lineEdit_name.setSizePolicy(sizePolicy)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.horizontalLayout_2.addWidget(self.lineEdit_name)
        self.verticalLayout_2.addWidget(self.widget_name)
        self.widget_allow_siderball_tint = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_allow_siderball_tint.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_allow_siderball_tint.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widget_allow_siderball_tint.setObjectName("widget_allow_siderball_tint")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_allow_siderball_tint)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_allow_siderball_tint = QtWidgets.QLabel(self.widget_allow_siderball_tint)
        self.label_allow_siderball_tint.setObjectName("label_allow_siderball_tint")
        self.horizontalLayout_4.addWidget(self.label_allow_siderball_tint)
        self.checkBox_allow_siderball_tint = QtWidgets.QCheckBox(self.widget_allow_siderball_tint)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_allow_siderball_tint.sizePolicy().hasHeightForWidth())
        self.checkBox_allow_siderball_tint.setSizePolicy(sizePolicy)
        self.checkBox_allow_siderball_tint.setText("")
        self.checkBox_allow_siderball_tint.setObjectName("checkBox_allow_siderball_tint")
        self.horizontalLayout_4.addWidget(self.checkBox_allow_siderball_tint)
        self.verticalLayout_2.addWidget(self.widget_allow_siderball_tint)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scrollArea)
        self.tabWidget.addTab(self.tab_general, "")
        self.tab_colors = QtWidgets.QWidget()
        self.tab_colors.setObjectName("tab_colors")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_colors)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab_colors)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 414, 352))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.widget_combo1 = QtWidgets.QWidget(self.scrollAreaWidgetContents_3)
        self.widget_combo1.setGeometry(QtCore.QRect(10, 10, 396, 100))
        self.widget_combo1.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_combo1.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widget_combo1.setSizeIncrement(QtCore.QSize(0, 0))
        self.widget_combo1.setObjectName("widget_combo1")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout(self.widget_combo1)
        self.horizontalLayout_33.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_33.setSpacing(0)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.label_combo1 = QtWidgets.QLabel(self.widget_combo1)
        self.label_combo1.setObjectName("label_combo1")
        self.horizontalLayout_33.addWidget(self.label_combo1)
        self.lineEdit_combo1 = QtWidgets.QLineEdit(self.widget_combo1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_combo1.sizePolicy().hasHeightForWidth())
        self.lineEdit_combo1.setSizePolicy(sizePolicy)
        self.lineEdit_combo1.setMaximumSize(QtCore.QSize(61, 16777215))
        self.lineEdit_combo1.setObjectName("lineEdit_combo1")
        self.horizontalLayout_33.addWidget(self.lineEdit_combo1)
        self.label_c_combo1 = QtWidgets.QLabel(self.widget_combo1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_c_combo1.sizePolicy().hasHeightForWidth())
        self.label_c_combo1.setSizePolicy(sizePolicy)
        self.label_c_combo1.setMinimumSize(QtCore.QSize(21, 21))
        self.label_c_combo1.setAutoFillBackground(False)
        self.label_c_combo1.setText("")
        self.label_c_combo1.setObjectName("label_c_combo1")
        self.horizontalLayout_33.addWidget(self.label_c_combo1)
        self.pushButton_combo1 = QtWidgets.QPushButton(self.widget_combo1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_combo1.sizePolicy().hasHeightForWidth())
        self.pushButton_combo1.setSizePolicy(sizePolicy)
        self.pushButton_combo1.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_combo1.setObjectName("pushButton_combo1")
        self.horizontalLayout_33.addWidget(self.pushButton_combo1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_4.addWidget(self.scrollArea_2)
        self.tabWidget.addTab(self.tab_colors, "")
        self.tab_fonts = QtWidgets.QWidget()
        self.tab_fonts.setObjectName("tab_fonts")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_fonts)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.tab_fonts)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 414, 352))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widget_author_5 = QtWidgets.QWidget(self.scrollAreaWidgetContents_4)
        self.widget_author_5.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_author_5.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widget_author_5.setSizeIncrement(QtCore.QSize(0, 0))
        self.widget_author_5.setObjectName("widget_author_5")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout(self.widget_author_5)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_author_5 = QtWidgets.QLabel(self.widget_author_5)
        self.label_author_5.setObjectName("label_author_5")
        self.horizontalLayout_31.addWidget(self.label_author_5)
        self.lineEdit_author_5 = QtWidgets.QLineEdit(self.widget_author_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_author_5.sizePolicy().hasHeightForWidth())
        self.lineEdit_author_5.setSizePolicy(sizePolicy)
        self.lineEdit_author_5.setObjectName("lineEdit_author_5")
        self.horizontalLayout_31.addWidget(self.lineEdit_author_5)
        self.verticalLayout_8.addWidget(self.widget_author_5)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_4)
        self.verticalLayout_6.addWidget(self.scrollArea_3)
        self.tabWidget.addTab(self.tab_fonts, "")
        self.tab_catch = QtWidgets.QWidget()
        self.tab_catch.setObjectName("tab_catch")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_catch)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.scrollArea_4 = QtWidgets.QScrollArea(self.tab_catch)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 414, 352))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_5)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.widget_hyper_dash = QtWidgets.QWidget(self.scrollAreaWidgetContents_5)
        self.widget_hyper_dash.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_hyper_dash.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widget_hyper_dash.setSizeIncrement(QtCore.QSize(0, 0))
        self.widget_hyper_dash.setObjectName("widget_hyper_dash")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout(self.widget_hyper_dash)
        self.horizontalLayout_32.setSpacing(0)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.label_hyper_dash = QtWidgets.QLabel(self.widget_hyper_dash)
        self.label_hyper_dash.setObjectName("label_hyper_dash")
        self.horizontalLayout_32.addWidget(self.label_hyper_dash)
        self.lineEdit_hyper_dash = QtWidgets.QLineEdit(self.widget_hyper_dash)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_hyper_dash.sizePolicy().hasHeightForWidth())
        self.lineEdit_hyper_dash.setSizePolicy(sizePolicy)
        self.lineEdit_hyper_dash.setMaximumSize(QtCore.QSize(61, 16777215))
        self.lineEdit_hyper_dash.setObjectName("lineEdit_hyper_dash")
        self.horizontalLayout_32.addWidget(self.lineEdit_hyper_dash)
        self.label_c_hyper_dash = QtWidgets.QLabel(self.widget_hyper_dash)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_c_hyper_dash.sizePolicy().hasHeightForWidth())
        self.label_c_hyper_dash.setSizePolicy(sizePolicy)
        self.label_c_hyper_dash.setMinimumSize(QtCore.QSize(21, 21))
        self.label_c_hyper_dash.setAutoFillBackground(False)
        self.label_c_hyper_dash.setText("")
        self.label_c_hyper_dash.setObjectName("label_c_hyper_dash")
        self.horizontalLayout_32.addWidget(self.label_c_hyper_dash)
        self.pushButton_hyper_dash = QtWidgets.QPushButton(self.widget_hyper_dash)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_hyper_dash.sizePolicy().hasHeightForWidth())
        self.pushButton_hyper_dash.setSizePolicy(sizePolicy)
        self.pushButton_hyper_dash.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_hyper_dash.setObjectName("pushButton_hyper_dash")
        self.horizontalLayout_32.addWidget(self.pushButton_hyper_dash)
        self.verticalLayout_9.addWidget(self.widget_hyper_dash)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_5)
        self.verticalLayout_7.addWidget(self.scrollArea_4)
        self.tabWidget.addTab(self.tab_catch, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_skin_ini_editor_header.setText(_translate("Dialog", "skin.ini editor"))
        self.pushButton_skin_ini_save.setText(_translate("Dialog", "Save"))
        self.label_name.setText(_translate("Dialog", "Name"))
        self.label_allow_siderball_tint.setText(_translate("Dialog", "AllowSliderBallTint"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_general), _translate("Dialog", "General"))
        self.label_combo1.setText(_translate("Dialog", "Combo1"))
        self.pushButton_combo1.setText(_translate("Dialog", "Select"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_colors), _translate("Dialog", "Colors"))
        self.label_author_5.setText(_translate("Dialog", "HitCircleOverlap"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_fonts), _translate("Dialog", "Fonts"))
        self.label_hyper_dash.setText(_translate("Dialog", "HyperDash"))
        self.pushButton_hyper_dash.setText(_translate("Dialog", "Select"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_catch), _translate("Dialog", "Catch"))

    def openColorDialog(self):
        return(QColorDialog.getColor())

    def initialisePreview(self, label, lineEdit):
        color=lineEdit.text()
        preview_img = Image.new("RGB", (21,21), color=self.rgbString2Tuple(color)))
        preview_img.save("preview.png")
        label.setPixmap(QPixmap("preview.png"))

    def rgbString2Tuple(self, rgb):
        try:
            r,g,b = rgb.split(",")
            t = (int(r),int(g),int(b))
        except:
            print("".join(["failed to convert: ",rgb,"to tuple"]))
            return (0,0,0)
        else:
            return t

    def createElements(self):
        self.elements = {}
"""

class Ui_MainWindow(object):

    #dialog_return = QtCore.pyqtSignal(str)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(954, 863)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_2.setEnabled(True)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 0, 941, 841))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_setup = QtWidgets.QWidget()
        self.tab_setup.setObjectName("tab_setup")
        self.label_title = QtWidgets.QLabel(self.tab_setup)
        self.label_title.setGeometry(QtCore.QRect(30, 20, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.plainTextEdit_skin_ini = QtWidgets.QPlainTextEdit(self.tab_setup)
        self.plainTextEdit_skin_ini.setGeometry(QtCore.QRect(30, 120, 600, 600))
        self.plainTextEdit_skin_ini.setObjectName("plainTextEdit_skin_ini")
        self.label_skin_ini = QtWidgets.QLabel(self.tab_setup)
        self.label_skin_ini.setGeometry(QtCore.QRect(30, 90, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_skin_ini.setFont(font)
        self.label_skin_ini.setObjectName("label_skin_ini")
        self.pushButton_edit_skin_ini = QtWidgets.QPushButton(self.tab_setup)
        self.pushButton_edit_skin_ini.setGeometry(QtCore.QRect(100, 90, 75, 23))
        self.pushButton_edit_skin_ini.setObjectName("pushButton_edit_skin_ini")
        self.tabWidget_2.addTab(self.tab_setup, "")
        self.tab_UI = QtWidgets.QWidget()
        self.tab_UI.setObjectName("tab_UI")
        self.tabWidget = QtWidgets.QTabWidget(self.tab_UI)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 941, 841))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_main_menu = QtWidgets.QWidget()
        self.tab_main_menu.setObjectName("tab_main_menu")
        self.label_header_main_menu = QtWidgets.QLabel(self.tab_main_menu)
        self.label_header_main_menu.setGeometry(QtCore.QRect(30, 20, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_header_main_menu.setFont(font)
        self.label_header_main_menu.setObjectName("label_header_main_menu")
        self.tabWidget.addTab(self.tab_main_menu, "")
        self.tab_cursor = QtWidgets.QWidget()
        self.tab_cursor.setObjectName("tab_cursor")
        self.label_header_cursor = QtWidgets.QLabel(self.tab_cursor)
        self.label_header_cursor.setGeometry(QtCore.QRect(30, 20, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_header_cursor.setFont(font)
        self.label_header_cursor.setObjectName("label_header_cursor")
        self.tabWidget.addTab(self.tab_cursor, "")
        self.tab_song_selection = QtWidgets.QWidget()
        self.tab_song_selection.setObjectName("tab_song_selection")
        self.label_header_song_selection = QtWidgets.QLabel(self.tab_song_selection)
        self.label_header_song_selection.setGeometry(QtCore.QRect(30, 20, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_header_song_selection.setFont(font)
        self.label_header_song_selection.setObjectName("label_header_song_selection")
        self.tabWidget.addTab(self.tab_song_selection, "")
        self.tab_mod_selection = QtWidgets.QWidget()
        self.tab_mod_selection.setObjectName("tab_mod_selection")
        self.label_header_mod_selection = QtWidgets.QLabel(self.tab_mod_selection)
        self.label_header_mod_selection.setGeometry(QtCore.QRect(30, 20, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_header_mod_selection.setFont(font)
        self.label_header_mod_selection.setObjectName("label_header_mod_selection")
        self.tabWidget.addTab(self.tab_mod_selection, "")
        self.tab_gamemode = QtWidgets.QWidget()
        self.tab_gamemode.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tab_gamemode.setObjectName("tab_gamemode")
        self.label_header_gamemode = QtWidgets.QLabel(self.tab_gamemode)
        self.label_header_gamemode.setGeometry(QtCore.QRect(30, 20, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_header_gamemode.setFont(font)
        self.label_header_gamemode.setObjectName("label_header_gamemode")
        self.tabWidget.addTab(self.tab_gamemode, "")
        self.tab_grade = QtWidgets.QWidget()
        self.tab_grade.setObjectName("tab_grade")
        self.label_header_grade = QtWidgets.QLabel(self.tab_grade)
        self.label_header_grade.setGeometry(QtCore.QRect(30, 20, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_header_grade.setFont(font)
        self.label_header_grade.setObjectName("label_header_grade")
        self.tabWidget.addTab(self.tab_grade, "")
        self.tab_score_numbers = QtWidgets.QWidget()
        self.tab_score_numbers.setObjectName("tab_score_numbers")
        self.label_header_score_numbers = QtWidgets.QLabel(self.tab_score_numbers)
        self.label_header_score_numbers.setGeometry(QtCore.QRect(30, 20, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_header_score_numbers.setFont(font)
        self.label_header_score_numbers.setObjectName("label_header_score_numbers")
        self.tabWidget.addTab(self.tab_score_numbers, "")
        self.tabWidget_2.addTab(self.tab_UI, "")
        self.tab_gameplay = QtWidgets.QWidget()
        self.tab_gameplay.setObjectName("tab_gameplay")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.tab_gameplay)
        self.tabWidget_3.setGeometry(QtCore.QRect(0, 0, 941, 821))
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_pause_screen = QtWidgets.QWidget()
        self.tab_pause_screen.setObjectName("tab_pause_screen")
        self.label_header_cursor_2 = QtWidgets.QLabel(self.tab_pause_screen)
        self.label_header_cursor_2.setGeometry(QtCore.QRect(30, 20, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_header_cursor_2.setFont(font)
        self.label_header_cursor_2.setObjectName("label_header_cursor_2")
        self.tabWidget_3.addTab(self.tab_pause_screen, "")
        self.tab_scorebar = QtWidgets.QWidget()
        self.tab_scorebar.setObjectName("tab_scorebar")
        self.label_header_scorebar = QtWidgets.QLabel(self.tab_scorebar)
        self.label_header_scorebar.setGeometry(QtCore.QRect(30, 20, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_header_scorebar.setFont(font)
        self.label_header_scorebar.setObjectName("label_header_scorebar")
        self.tabWidget_3.addTab(self.tab_scorebar, "")
        self.tab_countdown = QtWidgets.QWidget()
        self.tab_countdown.setObjectName("tab_countdown")
        self.label_header_countdown = QtWidgets.QLabel(self.tab_countdown)
        self.label_header_countdown.setGeometry(QtCore.QRect(30, 20, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_header_countdown.setFont(font)
        self.label_header_countdown.setObjectName("label_header_countdown")
        self.tabWidget_3.addTab(self.tab_countdown, "")
        self.tab_leaderboard = QtWidgets.QWidget()
        self.tab_leaderboard.setObjectName("tab_leaderboard")
        self.label_header_leaderboard = QtWidgets.QLabel(self.tab_leaderboard)
        self.label_header_leaderboard.setGeometry(QtCore.QRect(30, 20, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_header_leaderboard.setFont(font)
        self.label_header_leaderboard.setObjectName("label_header_leaderboard")
        self.tabWidget_3.addTab(self.tab_leaderboard, "")
        self.tab_playfield = QtWidgets.QWidget()
        self.tab_playfield.setObjectName("tab_playfield")
        self.label_header_playfield = QtWidgets.QLabel(self.tab_playfield)
        self.label_header_playfield.setGeometry(QtCore.QRect(30, 20, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_header_playfield.setFont(font)
        self.label_header_playfield.setObjectName("label_header_playfield")
        self.tabWidget_3.addTab(self.tab_playfield, "")
        self.tab_key_counter = QtWidgets.QWidget()
        self.tab_key_counter.setObjectName("tab_key_counter")
        self.label_header_key_counter = QtWidgets.QLabel(self.tab_key_counter)
        self.label_header_key_counter.setGeometry(QtCore.QRect(30, 20, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_header_key_counter.setFont(font)
        self.label_header_key_counter.setObjectName("label_header_key_counter")
        self.tabWidget_3.addTab(self.tab_key_counter, "")
        self.tabWidget_2.addTab(self.tab_gameplay, "")
        self.tab_standard = QtWidgets.QWidget()
        self.tab_standard.setObjectName("tab_standard")
        self.tabWidget_4 = QtWidgets.QTabWidget(self.tab_standard)
        self.tabWidget_4.setGeometry(QtCore.QRect(0, 0, 941, 821))
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_hitcircle_numbers = QtWidgets.QWidget()
        self.tab_hitcircle_numbers.setObjectName("tab_hitcircle_numbers")
        self.label_header_standard_hitcircle_numbers = QtWidgets.QLabel(self.tab_hitcircle_numbers)
        self.label_header_standard_hitcircle_numbers.setGeometry(QtCore.QRect(30, 20, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_header_standard_hitcircle_numbers.setFont(font)
        self.label_header_standard_hitcircle_numbers.setObjectName("label_header_standard_hitcircle_numbers")
        self.tabWidget_4.addTab(self.tab_hitcircle_numbers, "")
        self.tab_hitcircle_object = QtWidgets.QWidget()
        self.tab_hitcircle_object.setObjectName("tab_hitcircle_object")
        self.label_header_standard_hitcircles = QtWidgets.QLabel(self.tab_hitcircle_object)
        self.label_header_standard_hitcircles.setGeometry(QtCore.QRect(30, 20, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_header_standard_hitcircles.setFont(font)
        self.label_header_standard_hitcircles.setObjectName("label_header_standard_hitcircles")
        self.tabWidget_4.addTab(self.tab_hitcircle_object, "")
        self.tab_spinner = QtWidgets.QWidget()
        self.tab_spinner.setObjectName("tab_spinner")
        self.label_header_standard_spinner = QtWidgets.QLabel(self.tab_spinner)
        self.label_header_standard_spinner.setGeometry(QtCore.QRect(30, 20, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_header_standard_spinner.setFont(font)
        self.label_header_standard_spinner.setObjectName("label_header_standard_spinner")
        self.tabWidget_4.addTab(self.tab_spinner, "")
        self.tab_slidertrack = QtWidgets.QWidget()
        self.tab_slidertrack.setObjectName("tab_slidertrack")
        self.label_header_standard_slidertrack = QtWidgets.QLabel(self.tab_slidertrack)
        self.label_header_standard_slidertrack.setGeometry(QtCore.QRect(30, 20, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_header_standard_slidertrack.setFont(font)
        self.label_header_standard_slidertrack.setObjectName("label_header_standard_slidertrack")
        self.tabWidget_4.addTab(self.tab_slidertrack, "")
        self.tab_hitbursts = QtWidgets.QWidget()
        self.tab_hitbursts.setObjectName("tab_hitbursts")
        self.label_header_standard_hitbursts = QtWidgets.QLabel(self.tab_hitbursts)
        self.label_header_standard_hitbursts.setGeometry(QtCore.QRect(30, 20, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_header_standard_hitbursts.setFont(font)
        self.label_header_standard_hitbursts.setObjectName("label_header_standard_hitbursts")
        self.tabWidget_4.addTab(self.tab_hitbursts, "")
        self.tabWidget_2.addTab(self.tab_standard, "")
        self.tab_mania = QtWidgets.QWidget()
        self.tab_mania.setObjectName("tab_mania")
        self.tabWidget_7 = QtWidgets.QTabWidget(self.tab_mania)
        self.tabWidget_7.setGeometry(QtCore.QRect(0, 0, 941, 821))
        self.tabWidget_7.setObjectName("tabWidget_7")
        self.tab_mania_stage = QtWidgets.QWidget()
        self.tab_mania_stage.setObjectName("tab_mania_stage")
        self.label_header_standard_hitbursts_2 = QtWidgets.QLabel(self.tab_mania_stage)
        self.label_header_standard_hitbursts_2.setGeometry(QtCore.QRect(30, 20, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_header_standard_hitbursts_2.setFont(font)
        self.label_header_standard_hitbursts_2.setObjectName("label_header_standard_hitbursts_2")
        self.tabWidget_7.addTab(self.tab_mania_stage, "")
        self.tab_mania_keys = QtWidgets.QWidget()
        self.tab_mania_keys.setObjectName("tab_mania_keys")
        self.label_header_standard_hitbursts_3 = QtWidgets.QLabel(self.tab_mania_keys)
        self.label_header_standard_hitbursts_3.setGeometry(QtCore.QRect(30, 20, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_header_standard_hitbursts_3.setFont(font)
        self.label_header_standard_hitbursts_3.setObjectName("label_header_standard_hitbursts_3")
        self.tabWidget_7.addTab(self.tab_mania_keys, "")
        self.tab_mania_notes = QtWidgets.QWidget()
        self.tab_mania_notes.setObjectName("tab_mania_notes")
        self.label_header_standard_hitbursts_4 = QtWidgets.QLabel(self.tab_mania_notes)
        self.label_header_standard_hitbursts_4.setGeometry(QtCore.QRect(30, 20, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_header_standard_hitbursts_4.setFont(font)
        self.label_header_standard_hitbursts_4.setObjectName("label_header_standard_hitbursts_4")
        self.tabWidget_7.addTab(self.tab_mania_notes, "")
        self.tab_mania_hitbursts = QtWidgets.QWidget()
        self.tab_mania_hitbursts.setObjectName("tab_mania_hitbursts")
        self.label_header_standard_hitbursts_5 = QtWidgets.QLabel(self.tab_mania_hitbursts)
        self.label_header_standard_hitbursts_5.setGeometry(QtCore.QRect(30, 20, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_header_standard_hitbursts_5.setFont(font)
        self.label_header_standard_hitbursts_5.setObjectName("label_header_standard_hitbursts_5")
        self.tabWidget_7.addTab(self.tab_mania_hitbursts, "")
        self.tabWidget_2.addTab(self.tab_mania, "")
        self.tab_taiko = QtWidgets.QWidget()
        self.tab_taiko.setObjectName("tab_taiko")
        self.tabWidget_5 = QtWidgets.QTabWidget(self.tab_taiko)
        self.tabWidget_5.setGeometry(QtCore.QRect(0, 0, 941, 821))
        self.tabWidget_5.setObjectName("tabWidget_5")
        self.tab_taiko_pippidon = QtWidgets.QWidget()
        self.tab_taiko_pippidon.setObjectName("tab_taiko_pippidon")
        self.label_header_standard_hitbursts_6 = QtWidgets.QLabel(self.tab_taiko_pippidon)
        self.label_header_standard_hitbursts_6.setGeometry(QtCore.QRect(30, 20, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_header_standard_hitbursts_6.setFont(font)
        self.label_header_standard_hitbursts_6.setObjectName("label_header_standard_hitbursts_6")
        self.tabWidget_5.addTab(self.tab_taiko_pippidon, "")
        self.tab_taiko_slider_bar = QtWidgets.QWidget()
        self.tab_taiko_slider_bar.setObjectName("tab_taiko_slider_bar")
        self.label_header_standard_hitbursts_7 = QtWidgets.QLabel(self.tab_taiko_slider_bar)
        self.label_header_standard_hitbursts_7.setGeometry(QtCore.QRect(30, 20, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_header_standard_hitbursts_7.setFont(font)
        self.label_header_standard_hitbursts_7.setObjectName("label_header_standard_hitbursts_7")
        self.tabWidget_5.addTab(self.tab_taiko_slider_bar, "")
        self.tab_taiko_drum_bar = QtWidgets.QWidget()
        self.tab_taiko_drum_bar.setObjectName("tab_taiko_drum_bar")
        self.label_header_standard_hitbursts_8 = QtWidgets.QLabel(self.tab_taiko_drum_bar)
        self.label_header_standard_hitbursts_8.setGeometry(QtCore.QRect(30, 20, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_header_standard_hitbursts_8.setFont(font)
        self.label_header_standard_hitbursts_8.setObjectName("label_header_standard_hitbursts_8")
        self.tabWidget_5.addTab(self.tab_taiko_drum_bar, "")
        self.tab_taiko_notes = QtWidgets.QWidget()
        self.tab_taiko_notes.setObjectName("tab_taiko_notes")
        self.label_header_standard_hitbursts_9 = QtWidgets.QLabel(self.tab_taiko_notes)
        self.label_header_standard_hitbursts_9.setGeometry(QtCore.QRect(30, 20, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_header_standard_hitbursts_9.setFont(font)
        self.label_header_standard_hitbursts_9.setObjectName("label_header_standard_hitbursts_9")
        self.tabWidget_5.addTab(self.tab_taiko_notes, "")
        self.tab_taiko_drumroll = QtWidgets.QWidget()
        self.tab_taiko_drumroll.setObjectName("tab_taiko_drumroll")
        self.label_header_standard_hitbursts_10 = QtWidgets.QLabel(self.tab_taiko_drumroll)
        self.label_header_standard_hitbursts_10.setGeometry(QtCore.QRect(30, 20, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_header_standard_hitbursts_10.setFont(font)
        self.label_header_standard_hitbursts_10.setObjectName("label_header_standard_hitbursts_10")
        self.tabWidget_5.addTab(self.tab_taiko_drumroll, "")
        self.tab_taiko_swell = QtWidgets.QWidget()
        self.tab_taiko_swell.setObjectName("tab_taiko_swell")
        self.label_header_standard_hitbursts_11 = QtWidgets.QLabel(self.tab_taiko_swell)
        self.label_header_standard_hitbursts_11.setGeometry(QtCore.QRect(30, 20, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_header_standard_hitbursts_11.setFont(font)
        self.label_header_standard_hitbursts_11.setObjectName("label_header_standard_hitbursts_11")
        self.tabWidget_5.addTab(self.tab_taiko_swell, "")
        self.tab_taiko_hitbursts = QtWidgets.QWidget()
        self.tab_taiko_hitbursts.setObjectName("tab_taiko_hitbursts")
        self.label_header_standard_hitbursts_12 = QtWidgets.QLabel(self.tab_taiko_hitbursts)
        self.label_header_standard_hitbursts_12.setGeometry(QtCore.QRect(30, 20, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_header_standard_hitbursts_12.setFont(font)
        self.label_header_standard_hitbursts_12.setObjectName("label_header_standard_hitbursts_12")
        self.tabWidget_5.addTab(self.tab_taiko_hitbursts, "")
        self.tabWidget_2.addTab(self.tab_taiko, "")
        self.tab_catch = QtWidgets.QWidget()
        self.tab_catch.setObjectName("tab_catch")
        self.tabWidget_6 = QtWidgets.QTabWidget(self.tab_catch)
        self.tabWidget_6.setGeometry(QtCore.QRect(0, 0, 941, 821))
        self.tabWidget_6.setObjectName("tabWidget_6")
        self.tab_catch_catcher = QtWidgets.QWidget()
        self.tab_catch_catcher.setObjectName("tab_catch_catcher")
        self.label_header_standard_hitbursts_13 = QtWidgets.QLabel(self.tab_catch_catcher)
        self.label_header_standard_hitbursts_13.setGeometry(QtCore.QRect(30, 20, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_header_standard_hitbursts_13.setFont(font)
        self.label_header_standard_hitbursts_13.setObjectName("label_header_standard_hitbursts_13")
        self.tabWidget_6.addTab(self.tab_catch_catcher, "")
        self.tab_catch_fruits = QtWidgets.QWidget()
        self.tab_catch_fruits.setObjectName("tab_catch_fruits")
        self.label_header_standard_hitbursts_14 = QtWidgets.QLabel(self.tab_catch_fruits)
        self.label_header_standard_hitbursts_14.setGeometry(QtCore.QRect(30, 20, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_header_standard_hitbursts_14.setFont(font)
        self.label_header_standard_hitbursts_14.setObjectName("label_header_standard_hitbursts_14")
        self.tabWidget_6.addTab(self.tab_catch_fruits, "")
        self.tabWidget_2.addTab(self.tab_catch, "")
        self.tab_completion = QtWidgets.QWidget()
        self.tab_completion.setObjectName("tab_completion")
        self.label_completion = QtWidgets.QLabel(self.tab_completion)
        self.label_completion.setGeometry(QtCore.QRect(30, 20, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_completion.setFont(font)
        self.label_completion.setObjectName("label_completion")
        self.label_output_folder = QtWidgets.QLabel(self.tab_completion)
        self.label_output_folder.setGeometry(QtCore.QRect(30, 60, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_output_folder.setFont(font)
        self.label_output_folder.setObjectName("label_output_folder")
        self.pushButton_output_folder = QtWidgets.QPushButton(self.tab_completion)
        self.pushButton_output_folder.setGeometry(QtCore.QRect(420, 60, 75, 23))
        self.pushButton_output_folder.setObjectName("pushButton_output_folder")
        self.lineEdit_output_folder = QtWidgets.QLineEdit(self.tab_completion)
        self.lineEdit_output_folder.setGeometry(QtCore.QRect(160, 60, 241, 20))
        self.lineEdit_output_folder.setObjectName("lineEdit_output_folder")
        self.pushButton_create_skin = QtWidgets.QPushButton(self.tab_completion)
        self.pushButton_create_skin.setGeometry(QtCore.QRect(260, 130, 111, 41))
        self.pushButton_create_skin.setObjectName("pushButton_create_skin")
        self.tabWidget_2.addTab(self.tab_completion, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew_Skin = QtWidgets.QAction(MainWindow)
        self.actionNew_Skin.setObjectName("actionNew_Skin")

        ######################USER
        with open('fields.json','r') as f:
            self.fields = json.loads(f.read())
        self.createFields()
        print("complete")
        #####################NON USER

        self.retranslateUi(MainWindow)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        self.tabWidget_4.setCurrentIndex(0)
        self.tabWidget_7.setCurrentIndex(0)
        self.tabWidget_5.setCurrentIndex(0)
        self.tabWidget_6.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        ###############################

        #self.pushButton_menu_background.clicked.connect(lambda: self.add_element(self.lineEdit_menu_background))
        #self.pushButton_welcome.clicked.connect(lambda: self.add_element(self.lineEdit_welcome))
        #self.pushButton_menu_snow.clicked.connect(lambda: self.add_element(self.lineEdit_menu_snow))
        #self.pushButton_options_offset_tick.clicked.connect(lambda: self.add_element(self.lineEdit_options_offset_tick))
        self.pushButton_output_folder.clicked.connect(lambda: self.selectDirectory(self.lineEdit_output_folder))
        with open('skin.ini', 'r') as f:
            self.plainTextEdit_skin_ini.document().setPlainText(f.read())
        self.pushButton_create_skin.clicked.connect(lambda: self.complete_skin())


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Osu Skin Helper"))
        self.label_title.setText(_translate("MainWindow", "Osu Skin Helper"))
        self.label_skin_ini.setText(_translate("MainWindow", "skin.ini"))
        self.pushButton_edit_skin_ini.setText(_translate("MainWindow", "Editor"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_setup), _translate("MainWindow", "Setup"))
        self.label_header_main_menu.setText(_translate("MainWindow", "Main Menu"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_main_menu), _translate("MainWindow", "Main Menu"))
        self.label_header_cursor.setText(_translate("MainWindow", "Cursor"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_cursor), _translate("MainWindow", "Cursor"))
        self.label_header_song_selection.setText(_translate("MainWindow", "Song Selection"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_song_selection), _translate("MainWindow", "Song Selection"))
        self.label_header_mod_selection.setText(_translate("MainWindow", "Mod Selection"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_mod_selection), _translate("MainWindow", "Mod Selection"))
        self.label_header_gamemode.setText(_translate("MainWindow", "Gamemode"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_gamemode), _translate("MainWindow", "Gamemode"))
        self.label_header_grade.setText(_translate("MainWindow", "Results Screen"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_grade), _translate("MainWindow", "Results Screen"))
        self.label_header_score_numbers.setText(_translate("MainWindow", "Score Numbers"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_score_numbers), _translate("MainWindow", "Score Number"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_UI), _translate("MainWindow", "UI Elements"))
        self.label_header_cursor_2.setText(_translate("MainWindow", "Pause Screen"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_pause_screen), _translate("MainWindow", "Pause Screen"))
        self.label_header_scorebar.setText(_translate("MainWindow", "Scorebar"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_scorebar), _translate("MainWindow", "Scorebar"))
        self.label_header_countdown.setText(_translate("MainWindow", "Countdown"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_countdown), _translate("MainWindow", "Countdown"))
        self.label_header_leaderboard.setText(_translate("MainWindow", "Leaderboard"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_leaderboard), _translate("MainWindow", "Leaderboard"))
        self.label_header_playfield.setText(_translate("MainWindow", "Playfield"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_playfield), _translate("MainWindow", "Playfield"))
        self.label_header_key_counter.setText(_translate("MainWindow", "Key Counter"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_key_counter), _translate("MainWindow", "Key Counter"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_gameplay), _translate("MainWindow", "Gameplay"))
        self.label_header_standard_hitcircle_numbers.setText(_translate("MainWindow", "Hitcircle Numbers"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_hitcircle_numbers), _translate("MainWindow", "Hitcircle Numbers"))
        self.label_header_standard_hitcircles.setText(_translate("MainWindow", "Hitcircles"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_hitcircle_object), _translate("MainWindow", "Hitcircles"))
        self.label_header_standard_spinner.setText(_translate("MainWindow", "Spinner"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_spinner), _translate("MainWindow", "Spinner"))
        self.label_header_standard_slidertrack.setText(_translate("MainWindow", "Slidertrack"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_slidertrack), _translate("MainWindow", "Slidertrack"))
        self.label_header_standard_hitbursts.setText(_translate("MainWindow", "Hitbursts"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_hitbursts), _translate("MainWindow", "Hitbursts"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_standard), _translate("MainWindow", "Standard"))
        self.label_header_standard_hitbursts_2.setText(_translate("MainWindow", "Stage"))
        self.tabWidget_7.setTabText(self.tabWidget_7.indexOf(self.tab_mania_stage), _translate("MainWindow", "Stage"))
        self.label_header_standard_hitbursts_3.setText(_translate("MainWindow", "Keys"))
        self.tabWidget_7.setTabText(self.tabWidget_7.indexOf(self.tab_mania_keys), _translate("MainWindow", "Keys"))
        self.label_header_standard_hitbursts_4.setText(_translate("MainWindow", "Notes"))
        self.tabWidget_7.setTabText(self.tabWidget_7.indexOf(self.tab_mania_notes), _translate("MainWindow", "Notes"))
        self.label_header_standard_hitbursts_5.setText(_translate("MainWindow", "Hitbursts"))
        self.tabWidget_7.setTabText(self.tabWidget_7.indexOf(self.tab_mania_hitbursts), _translate("MainWindow", "Hitbursts"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_mania), _translate("MainWindow", "Mania"))
        self.label_header_standard_hitbursts_6.setText(_translate("MainWindow", "Pippidon"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_taiko_pippidon), _translate("MainWindow", "Pippidon"))
        self.label_header_standard_hitbursts_7.setText(_translate("MainWindow", "Slider Bar"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_taiko_slider_bar), _translate("MainWindow", "Slider Bar"))
        self.label_header_standard_hitbursts_8.setText(_translate("MainWindow", "Drum Bar"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_taiko_drum_bar), _translate("MainWindow", "Drum Bar"))
        self.label_header_standard_hitbursts_9.setText(_translate("MainWindow", "Notes"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_taiko_notes), _translate("MainWindow", "Notes"))
        self.label_header_standard_hitbursts_10.setText(_translate("MainWindow", "Drumroll"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_taiko_drumroll), _translate("MainWindow", "Drumroll"))
        self.label_header_standard_hitbursts_11.setText(_translate("MainWindow", "Swell"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_taiko_swell), _translate("MainWindow", "Swell"))
        self.label_header_standard_hitbursts_12.setText(_translate("MainWindow", "Hitbursts"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_taiko_hitbursts), _translate("MainWindow", "Hitbursts"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_taiko), _translate("MainWindow", "Taiko"))
        self.label_header_standard_hitbursts_13.setText(_translate("MainWindow", "Catcher + Playfield"))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.tab_catch_catcher), _translate("MainWindow", "Catcher + Playfield"))
        self.label_header_standard_hitbursts_14.setText(_translate("MainWindow", "Fruits"))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.tab_catch_fruits), _translate("MainWindow", "Fruits"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_catch), _translate("MainWindow", "Catch"))
        self.label_completion.setText(_translate("MainWindow", "Completion"))
        self.label_output_folder.setText(_translate("MainWindow", "Output Location"))
        self.pushButton_output_folder.setText(_translate("MainWindow", "Select"))
        self.pushButton_create_skin.setText(_translate("MainWindow", "Create Skin!"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_completion), _translate("MainWindow", "Completion"))
        self.actionNew_Skin.setText(_translate("MainWindow", "New Skin"))
        ##########################################
        """self.fields = {  "UI": {
                        "main_menu" : {
                            "Menu Background": {},
                            "Welcome" : {},
                            "Menu Snow": {},
                            "Options Offset Tick" : {}
                        },
                        "cursor" : {
                            "Cursor" : {},
                            "Cursor Trail" : {},
                            "Cursor Middle" : {},
                            "Cursor Smoke" : {},
                            "Cursor Ripple" : {}
                        },
                        "song_selection" : {},
                        "mod_selection" : {},
                        "gamemode" : {},
                        "grade" : {},
                        "score_numbers" : {}
                    },
                    "gameplay" : {
                        "pause_screen" : {},
                        "scorebar" : {},
                        "countdown" : {},
                        "leaderboard" : {},
                        "playfield" : {},
                        "key_counter" : {}
                    },
                    "standard" : {
                        "hitcircle_numbers" : {},
                        "slidertrack" : {},
                        "spinner" : {},
                        "hitbursts" : {}
                    },
                    "mania" : {
                        "mania_stage" : {},
                        "mania_keys" : {},
                        "mania_notes" : {},
                        "mania_hitbursts" : {}
                    },
                    "taiko" : {
                        "taiko_pippidon" : {},
                        "taiko_slider_bar" : {},
                        "taiko_drum_bar" : {},
                        "taiko_notes" : {},
                        "taiko_drumroll" : {},
                        "taiko_swell" : {},
                        "taiko_hitbursts" : {}
                    },
                    "catch" : {
                        "catch_catcher" : {},
                        "catch_fruits" : {}
                    }
                    }"""
        self.addUiText()


    def createFields(self):
        start_x = 40
        start_y = 60
        delta_x = 410
        delta_y = 40
        delta_lineEdit = 230
        delta_pushButton = 120
        for tab_a in self.fields:
            for tab_b in self.fields[tab_a]:
                i = 0
                for field in self.fields[tab_a][tab_b]:
                    row = int(i / 2)
                    col = i % 2
                    self.fields[tab_a][tab_b][field]["lineEdit"] = QtWidgets.QLineEdit(eval("self.tab_" + tab_b))
                    self.fields[tab_a][tab_b][field]["lineEdit"].setEnabled(True)
                    self.fields[tab_a][tab_b][field]["lineEdit"].setGeometry(QtCore.QRect(start_x + delta_x * col + delta_lineEdit, start_y + delta_y * row, 113, 20))
                    self.fields[tab_a][tab_b][field]["lineEdit"].setObjectName("lineEdit_" + field)
                    self.fields[tab_a][tab_b][field]["label"] = QtWidgets.QLabel(eval("self.tab_" + tab_b))
                    self.fields[tab_a][tab_b][field]["label"].setGeometry(QtCore.QRect(start_x + delta_x * col , start_y + delta_y * row, 111, 16))
                    self.fields[tab_a][tab_b][field]["label"].setObjectName("label_" + field)
                    self.fields[tab_a][tab_b][field]["pushButton"] = QtWidgets.QPushButton(eval("self.tab_" + tab_b))
                    self.fields[tab_a][tab_b][field]["pushButton"].setGeometry(QtCore.QRect(start_x + delta_x * col + delta_pushButton, start_y + delta_y * row, 75, 23))
                    self.fields[tab_a][tab_b][field]["pushButton"].setObjectName("pushButton_" + field)

                    lineEdit = self.fields[tab_a][tab_b][field]["lineEdit"]
                    self.fields[tab_a][tab_b][field]["pushButton"].clicked.connect(lambda ignore,tab_a=tab_a,tab_b=tab_b,field=field: self.add_element(self.fields[tab_a][tab_b][field]["lineEdit"], field))
                    i += 1

    def addUiText(self):
        for tab_a in self.fields:
            for tab_b in self.fields[tab_a]:
                for field in self.fields[tab_a][tab_b]:
                    self.fields[tab_a][tab_b][field]["label"].setText(field)
                    self.fields[tab_a][tab_b][field]["pushButton"].setText("Select")

    def add_element(self, lineEdit, element):
        print("AddElement")
        print(lineEdit)
        Dialog = QtWidgets.QDialog()
        ui_add_element = AddElement()
        ui_add_element.setupUi(Dialog, element)
        Dialog.show()
        Dialog.exec_()
        try:
            print("recieved", ui_add_element.return_value)
            lineEdit.setText(ui_add_element.return_value)
        except:
            print("failed to update")

    def openFileNameDialog(self):
        return(QFileDialog.getOpenFileName())

    def openDirectoryDialog(self):
        return(str(QFileDialog.getExistingDirectory(None, "Select Folder")))

    def selectFile(self, lineEdit):
        file,_ = self.openFileNameDialog()
        print(file)
        lineEdit.setText(file)

    def selectDirectory(self, lineEdit):
        file = self.openDirectoryDialog()
        print(file)
        lineEdit.setText(file)

    def complete_skin(self):
        skin_ini = self.plainTextEdit_skin_ini.toPlainText()
        skin_ini_lines = skin_ini.split('\n')
        for line in skin_ini_lines:
            if (line[:4] == "Name"):
                skin_name = line[5:]
        output_dir = "/".join([self.lineEdit_output_folder.text(), skin_name])
        if not os.path.exists(output_dir):
            os.mkdir(output_dir)
        os.chdir(output_dir)
        for tab_a in self.fields:
            for tab_b in self.fields[tab_a]:
                i = 0
                for field in self.fields[tab_a][tab_b]:
                    loc = self.fields[tab_a][tab_b][field]["lineEdit"].text()
                    if loc:
                        print(loc)
                        try:
                            shutil.copyfile(loc, "/".join([output_dir, "".join([field, ".".join(["@2x","png"])])]))
                        except:
                            print("invalid file name probably...")
        with open("/".join([output_dir, "skin.ini"]), "w") as f:
            f.write(skin_ini)

        msg = QMessageBox()
        msg.setIcon(QMessageBox.Information)

        msg.setText("Skin created!")
        msg.setInformativeText("    Remember to convert to an .osk if you want to share it.")
        msg.setWindowTitle("Skin complete!")
        msg.setStandardButtons(QMessageBox.Ok)
        msg.buttonClicked.connect(lambda: MainWindow.close())
        msg.exec_()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
