# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'osu_skin_helper.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget, QInputDialog, QFileDialog, QDialog
from PyQt5.QtGui import QPixmap
import add_element_01
import cursor_editor_01

import json


class AddElement(QInputDialog):

    #dialog_return = QtCore.pyqtSignal(str)

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(678, 303)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_add_element = QtWidgets.QLabel(self.widget)
        self.label_add_element.setObjectName("label_add_element")
        self.horizontalLayout.addWidget(self.label_add_element)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.lineEdit_filepath = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_filepath.setText("")
        self.lineEdit_filepath.setObjectName("lineEdit_filepath")
        self.horizontalLayout.addWidget(self.lineEdit_filepath)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.widget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.verticalLayout.addWidget(self.widget)
        self.label_preview = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_preview.sizePolicy().hasHeightForWidth())
        self.label_preview.setSizePolicy(sizePolicy)
        self.label_preview.setObjectName("label_preview")
        self.verticalLayout.addWidget(self.label_preview)
        self.label_image = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_image.sizePolicy().hasHeightForWidth())
        self.label_image.setSizePolicy(sizePolicy)
        self.label_image.setText("")
        self.label_image.setObjectName("label_image")
        self.verticalLayout.addWidget(self.label_image)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        ####

        self.pushButton.clicked.connect(self.selectFile)


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Select Skin Element"))
        self.label_add_element.setText(_translate("Dialog", "Add Element"))
        self.pushButton.setText(_translate("Dialog", "Select File"))
        self.label_preview.setText(_translate("Dialog", "Preview"))


    def openFileNameDialog(self):
        return(QFileDialog.getOpenFileName())

    def selectFile(self):
        file,_ = self.openFileNameDialog()
        print(file)
        self.label_image.setPixmap(QPixmap(file))
        self.lineEdit_filepath.setText(file)

    def confirm(self):
        self.return_value = self.lineEdit_filepath.text()
        #self.dialog_return.emit(return_value)

class Ui_MainWindow(object):

    dialog_return = QtCore.pyqtSignal(str)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(954, 863)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 0, 941, 841))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_setup = QtWidgets.QWidget()
        self.tab_setup.setObjectName("tab_setup")
        self.label_title = QtWidgets.QLabel(self.tab_setup)
        self.label_title.setGeometry(QtCore.QRect(30, 20, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.label_modes = QtWidgets.QLabel(self.tab_setup)
        self.label_modes.setGeometry(QtCore.QRect(30, 60, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_modes.setFont(font)
        self.label_modes.setObjectName("label_modes")
        self.checkBox = QtWidgets.QCheckBox(self.tab_setup)
        self.checkBox.setGeometry(QtCore.QRect(90, 60, 70, 17))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.tab_setup)
        self.checkBox_2.setGeometry(QtCore.QRect(180, 60, 70, 17))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.tab_setup)
        self.checkBox_3.setGeometry(QtCore.QRect(270, 60, 70, 17))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.tab_setup)
        self.checkBox_4.setGeometry(QtCore.QRect(350, 60, 70, 17))
        self.checkBox_4.setObjectName("checkBox_4")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.tab_setup)
        self.plainTextEdit.setGeometry(QtCore.QRect(30, 120, 571, 191))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label_skin_ini = QtWidgets.QLabel(self.tab_setup)
        self.label_skin_ini.setGeometry(QtCore.QRect(30, 90, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_skin_ini.setFont(font)
        self.label_skin_ini.setObjectName("label_skin_ini")
        self.tabWidget_2.addTab(self.tab_setup, "")
        self.tab_UI = QtWidgets.QWidget()
        self.tab_UI.setObjectName("tab_UI")
        self.tabWidget = QtWidgets.QTabWidget(self.tab_UI)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 941, 841))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_main_menu = QtWidgets.QWidget()
        self.tab_main_menu.setObjectName("tab_main_menu")
        self.label_header_main_menu = QtWidgets.QLabel(self.tab_main_menu)
        self.label_header_main_menu.setGeometry(QtCore.QRect(30, 10, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_header_main_menu.setFont(font)
        self.label_header_main_menu.setObjectName("label_header_main_menu")
        self.pushButton_98 = QtWidgets.QPushButton(self.tab_main_menu)
        self.pushButton_98.setGeometry(QtCore.QRect(160, 60, 75, 23))
        self.pushButton_98.setObjectName("pushButton_98")
        self.label_98 = QtWidgets.QLabel(self.tab_main_menu)
        self.label_98.setGeometry(QtCore.QRect(40, 60, 91, 16))
        self.label_98.setObjectName("label_98")
        self.lineEdit_98 = QtWidgets.QLineEdit(self.tab_main_menu)
        self.lineEdit_98.setEnabled(True)
        self.lineEdit_98.setGeometry(QtCore.QRect(270, 60, 113, 20))
        self.lineEdit_98.setObjectName("lineEdit_98")
        self.tabWidget.addTab(self.tab_main_menu, "")
        self.tab_cursor = QtWidgets.QWidget()
        self.tab_cursor.setObjectName("tab_cursor")
        self.label_header_cursor = QtWidgets.QLabel(self.tab_cursor)
        self.label_header_cursor.setGeometry(QtCore.QRect(30, 10, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_header_cursor.setFont(font)
        self.label_header_cursor.setObjectName("label_header_cursor")
        self.tabWidget.addTab(self.tab_cursor, "")
        self.tab_song_selection = QtWidgets.QWidget()
        self.tab_song_selection.setObjectName("tab_song_selection")
        self.label_header_song_selection = QtWidgets.QLabel(self.tab_song_selection)
        self.label_header_song_selection.setGeometry(QtCore.QRect(30, 10, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_header_song_selection.setFont(font)
        self.label_header_song_selection.setObjectName("label_header_song_selection")
        self.tabWidget.addTab(self.tab_song_selection, "")
        self.tab_mod_selection = QtWidgets.QWidget()
        self.tab_mod_selection.setObjectName("tab_mod_selection")
        self.label_header_mod_selection = QtWidgets.QLabel(self.tab_mod_selection)
        self.label_header_mod_selection.setGeometry(QtCore.QRect(30, 10, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_header_mod_selection.setFont(font)
        self.label_header_mod_selection.setObjectName("label_header_mod_selection")
        self.tabWidget.addTab(self.tab_mod_selection, "")
        self.tab_gamemode = QtWidgets.QWidget()
        self.tab_gamemode.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tab_gamemode.setObjectName("tab_gamemode")
        self.label_header_gamemode = QtWidgets.QLabel(self.tab_gamemode)
        self.label_header_gamemode.setGeometry(QtCore.QRect(30, 10, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_header_gamemode.setFont(font)
        self.label_header_gamemode.setObjectName("label_header_gamemode")
        self.tabWidget.addTab(self.tab_gamemode, "")
        self.tab_grade = QtWidgets.QWidget()
        self.tab_grade.setObjectName("tab_grade")
        self.label_header_grade = QtWidgets.QLabel(self.tab_grade)
        self.label_header_grade.setGeometry(QtCore.QRect(30, 10, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_header_grade.setFont(font)
        self.label_header_grade.setObjectName("label_header_grade")
        self.tabWidget.addTab(self.tab_grade, "")
        self.tab_score_numbers = QtWidgets.QWidget()
        self.tab_score_numbers.setObjectName("tab_score_numbers")
        self.label_header_score_numbers = QtWidgets.QLabel(self.tab_score_numbers)
        self.label_header_score_numbers.setGeometry(QtCore.QRect(30, 10, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_header_score_numbers.setFont(font)
        self.label_header_score_numbers.setObjectName("label_header_score_numbers")
        self.tabWidget.addTab(self.tab_score_numbers, "")
        self.tabWidget_2.addTab(self.tab_UI, "")
        self.tab_gameplay = QtWidgets.QWidget()
        self.tab_gameplay.setObjectName("tab_gameplay")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.tab_gameplay)
        self.tabWidget_3.setGeometry(QtCore.QRect(0, 0, 941, 821))
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_pause_screen = QtWidgets.QWidget()
        self.tab_pause_screen.setObjectName("tab_pause_screen")
        self.label_header_cursor_2 = QtWidgets.QLabel(self.tab_pause_screen)
        self.label_header_cursor_2.setGeometry(QtCore.QRect(30, 20, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_header_cursor_2.setFont(font)
        self.label_header_cursor_2.setObjectName("label_header_cursor_2")
        self.tabWidget_3.addTab(self.tab_pause_screen, "")
        self.tab_scorebar = QtWidgets.QWidget()
        self.tab_scorebar.setObjectName("tab_scorebar")
        self.label_header_scorebar = QtWidgets.QLabel(self.tab_scorebar)
        self.label_header_scorebar.setGeometry(QtCore.QRect(30, 20, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_header_scorebar.setFont(font)
        self.label_header_scorebar.setObjectName("label_header_scorebar")
        self.tabWidget_3.addTab(self.tab_scorebar, "")
        self.tab_countdown = QtWidgets.QWidget()
        self.tab_countdown.setObjectName("tab_countdown")
        self.label_header_countdown = QtWidgets.QLabel(self.tab_countdown)
        self.label_header_countdown.setGeometry(QtCore.QRect(30, 20, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_header_countdown.setFont(font)
        self.label_header_countdown.setObjectName("label_header_countdown")
        self.tabWidget_3.addTab(self.tab_countdown, "")
        self.tab_leaderboard = QtWidgets.QWidget()
        self.tab_leaderboard.setObjectName("tab_leaderboard")
        self.label_header_leaderboard = QtWidgets.QLabel(self.tab_leaderboard)
        self.label_header_leaderboard.setGeometry(QtCore.QRect(30, 20, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_header_leaderboard.setFont(font)
        self.label_header_leaderboard.setObjectName("label_header_leaderboard")
        self.tabWidget_3.addTab(self.tab_leaderboard, "")
        self.tab_playfield = QtWidgets.QWidget()
        self.tab_playfield.setObjectName("tab_playfield")
        self.label_header_playfield = QtWidgets.QLabel(self.tab_playfield)
        self.label_header_playfield.setGeometry(QtCore.QRect(30, 20, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_header_playfield.setFont(font)
        self.label_header_playfield.setObjectName("label_header_playfield")
        self.tabWidget_3.addTab(self.tab_playfield, "")
        self.tab_key_counter = QtWidgets.QWidget()
        self.tab_key_counter.setObjectName("tab_key_counter")
        self.label_header_key_counter = QtWidgets.QLabel(self.tab_key_counter)
        self.label_header_key_counter.setGeometry(QtCore.QRect(30, 20, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_header_key_counter.setFont(font)
        self.label_header_key_counter.setObjectName("label_header_key_counter")
        self.tabWidget_3.addTab(self.tab_key_counter, "")
        self.tabWidget_2.addTab(self.tab_gameplay, "")
        self.tab_standard = QtWidgets.QWidget()
        self.tab_standard.setObjectName("tab_standard")
        self.tabWidget_4 = QtWidgets.QTabWidget(self.tab_standard)
        self.tabWidget_4.setGeometry(QtCore.QRect(0, 0, 941, 821))
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_hitcircle_numbers = QtWidgets.QWidget()
        self.tab_hitcircle_numbers.setObjectName("tab_hitcircle_numbers")
        self.label_header_standard_hitcircle_numbers = QtWidgets.QLabel(self.tab_hitcircle_numbers)
        self.label_header_standard_hitcircle_numbers.setGeometry(QtCore.QRect(30, 20, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_header_standard_hitcircle_numbers.setFont(font)
        self.label_header_standard_hitcircle_numbers.setObjectName("label_header_standard_hitcircle_numbers")
        self.tabWidget_4.addTab(self.tab_hitcircle_numbers, "")
        self.tab_hitcircle_object = QtWidgets.QWidget()
        self.tab_hitcircle_object.setObjectName("tab_hitcircle_object")
        self.label_header_standard_hitcircles = QtWidgets.QLabel(self.tab_hitcircle_object)
        self.label_header_standard_hitcircles.setGeometry(QtCore.QRect(30, 20, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_header_standard_hitcircles.setFont(font)
        self.label_header_standard_hitcircles.setObjectName("label_header_standard_hitcircles")
        self.tabWidget_4.addTab(self.tab_hitcircle_object, "")
        self.tab_slidertrack = QtWidgets.QWidget()
        self.tab_slidertrack.setObjectName("tab_slidertrack")
        self.label_header_standard_slidertrack = QtWidgets.QLabel(self.tab_slidertrack)
        self.label_header_standard_slidertrack.setGeometry(QtCore.QRect(30, 20, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_header_standard_slidertrack.setFont(font)
        self.label_header_standard_slidertrack.setObjectName("label_header_standard_slidertrack")
        self.tabWidget_4.addTab(self.tab_slidertrack, "")
        self.tab_spinner = QtWidgets.QWidget()
        self.tab_spinner.setObjectName("tab_spinner")
        self.label_header_standard_spinner = QtWidgets.QLabel(self.tab_spinner)
        self.label_header_standard_spinner.setGeometry(QtCore.QRect(30, 20, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_header_standard_spinner.setFont(font)
        self.label_header_standard_spinner.setObjectName("label_header_standard_spinner")
        self.tabWidget_4.addTab(self.tab_spinner, "")
        self.tab_hitbursts = QtWidgets.QWidget()
        self.tab_hitbursts.setObjectName("tab_hitbursts")
        self.label_header_standard_hitbursts = QtWidgets.QLabel(self.tab_hitbursts)
        self.label_header_standard_hitbursts.setGeometry(QtCore.QRect(30, 20, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_header_standard_hitbursts.setFont(font)
        self.label_header_standard_hitbursts.setObjectName("label_header_standard_hitbursts")
        self.tabWidget_4.addTab(self.tab_hitbursts, "")
        self.tabWidget_2.addTab(self.tab_standard, "")
        self.tab_mania = QtWidgets.QWidget()
        self.tab_mania.setObjectName("tab_mania")
        self.tabWidget_7 = QtWidgets.QTabWidget(self.tab_mania)
        self.tabWidget_7.setGeometry(QtCore.QRect(0, 0, 941, 821))
        self.tabWidget_7.setObjectName("tabWidget_7")
        self.tab_mania_stage = QtWidgets.QWidget()
        self.tab_mania_stage.setObjectName("tab_mania_stage")
        self.tabWidget_7.addTab(self.tab_mania_stage, "")
        self.tab_mania_keys = QtWidgets.QWidget()
        self.tab_mania_keys.setObjectName("tab_mania_keys")
        self.tabWidget_7.addTab(self.tab_mania_keys, "")
        self.tab_mania_notes = QtWidgets.QWidget()
        self.tab_mania_notes.setObjectName("tab_mania_notes")
        self.tabWidget_7.addTab(self.tab_mania_notes, "")
        self.tab_mania_hitbursts = QtWidgets.QWidget()
        self.tab_mania_hitbursts.setObjectName("tab_mania_hitbursts")
        self.tabWidget_7.addTab(self.tab_mania_hitbursts, "")
        self.tabWidget_2.addTab(self.tab_mania, "")
        self.tab_taiko = QtWidgets.QWidget()
        self.tab_taiko.setObjectName("tab_taiko")
        self.tabWidget_5 = QtWidgets.QTabWidget(self.tab_taiko)
        self.tabWidget_5.setGeometry(QtCore.QRect(0, 0, 941, 821))
        self.tabWidget_5.setObjectName("tabWidget_5")
        self.tab_taiko_pippidon = QtWidgets.QWidget()
        self.tab_taiko_pippidon.setObjectName("tab_taiko_pippidon")
        self.tabWidget_5.addTab(self.tab_taiko_pippidon, "")
        self.tab_taiko_slider_bar = QtWidgets.QWidget()
        self.tab_taiko_slider_bar.setObjectName("tab_taiko_slider_bar")
        self.tabWidget_5.addTab(self.tab_taiko_slider_bar, "")
        self.tab_taiko_drum_bar = QtWidgets.QWidget()
        self.tab_taiko_drum_bar.setObjectName("tab_taiko_drum_bar")
        self.tabWidget_5.addTab(self.tab_taiko_drum_bar, "")
        self.tab_taiko_notes = QtWidgets.QWidget()
        self.tab_taiko_notes.setObjectName("tab_taiko_notes")
        self.tabWidget_5.addTab(self.tab_taiko_notes, "")
        self.tab_taiko_drumroll = QtWidgets.QWidget()
        self.tab_taiko_drumroll.setObjectName("tab_taiko_drumroll")
        self.tabWidget_5.addTab(self.tab_taiko_drumroll, "")
        self.tab_taiko_swell = QtWidgets.QWidget()
        self.tab_taiko_swell.setObjectName("tab_taiko_swell")
        self.tabWidget_5.addTab(self.tab_taiko_swell, "")
        self.tab_taiko_hitbursts = QtWidgets.QWidget()
        self.tab_taiko_hitbursts.setObjectName("tab_taiko_hitbursts")
        self.tabWidget_5.addTab(self.tab_taiko_hitbursts, "")
        self.tabWidget_2.addTab(self.tab_taiko, "")
        self.tab_catch = QtWidgets.QWidget()
        self.tab_catch.setObjectName("tab_catch")
        self.tabWidget_6 = QtWidgets.QTabWidget(self.tab_catch)
        self.tabWidget_6.setGeometry(QtCore.QRect(0, 0, 941, 821))
        self.tabWidget_6.setObjectName("tabWidget_6")
        self.tab_catch_catcher = QtWidgets.QWidget()
        self.tab_catch_catcher.setObjectName("tab_catch_catcher")
        self.tabWidget_6.addTab(self.tab_catch_catcher, "")
        self.tab_catch_fruits = QtWidgets.QWidget()
        self.tab_catch_fruits.setObjectName("tab_catch_fruits")
        self.tabWidget_6.addTab(self.tab_catch_fruits, "")
        self.tabWidget_2.addTab(self.tab_catch, "")
        self.tab_completion = QtWidgets.QWidget()
        self.tab_completion.setObjectName("tab_completion")
        self.label_completion = QtWidgets.QLabel(self.tab_completion)
        self.label_completion.setGeometry(QtCore.QRect(30, 20, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_completion.setFont(font)
        self.label_completion.setObjectName("label_completion")
        self.label_output_folder = QtWidgets.QLabel(self.tab_completion)
        self.label_output_folder.setGeometry(QtCore.QRect(30, 60, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_output_folder.setFont(font)
        self.label_output_folder.setObjectName("label_output_folder")
        self.pushButton_output_folder = QtWidgets.QPushButton(self.tab_completion)
        self.pushButton_output_folder.setGeometry(QtCore.QRect(420, 60, 75, 23))
        self.pushButton_output_folder.setObjectName("pushButton_output_folder")
        self.lineEdit_output_folder = QtWidgets.QLineEdit(self.tab_completion)
        self.lineEdit_output_folder.setGeometry(QtCore.QRect(160, 60, 241, 20))
        self.lineEdit_output_folder.setObjectName("lineEdit_output_folder")
        self.pushButton_create_skin = QtWidgets.QPushButton(self.tab_completion)
        self.pushButton_create_skin.setGeometry(QtCore.QRect(260, 130, 111, 41))
        self.pushButton_create_skin.setObjectName("pushButton_create_skin")
        self.tabWidget_2.addTab(self.tab_completion, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew_Skin = QtWidgets.QAction(MainWindow)
        self.actionNew_Skin.setObjectName("actionNew_Skin")

        ######################USER
        with open('fields.json','r') as f:
            self.fields = json.loads(f.read())
        self.createFields()
        #####################NON USER

        self.retranslateUi(MainWindow)
        self.tabWidget_2.setCurrentIndex(1)
        self.tabWidget.setCurrentIndex(1)
        self.tabWidget_3.setCurrentIndex(0)
        self.tabWidget_4.setCurrentIndex(0)
        self.tabWidget_7.setCurrentIndex(0)
        self.tabWidget_5.setCurrentIndex(6)
        self.tabWidget_6.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        ###############################

        #self.pushButton_menu_background.clicked.connect(lambda: self.add_element(self.lineEdit_menu_background))
        #self.pushButton_welcome.clicked.connect(lambda: self.add_element(self.lineEdit_welcome))
        #self.pushButton_menu_snow.clicked.connect(lambda: self.add_element(self.lineEdit_menu_snow))
        #self.pushButton_options_offset_tick.clicked.connect(lambda: self.add_element(self.lineEdit_options_offset_tick))




    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Osu Skin Helper"))
        self.label_title.setText(_translate("MainWindow", "Osu Skin Helper"))
        self.label_modes.setText(_translate("MainWindow", "Modes"))
        self.checkBox.setText(_translate("MainWindow", "Standard"))
        self.checkBox_2.setText(_translate("MainWindow", "Mania"))
        self.checkBox_3.setText(_translate("MainWindow", "Taiko"))
        self.checkBox_4.setText(_translate("MainWindow", "Catch"))
        self.label_skin_ini.setText(_translate("MainWindow", "skin.ini"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_setup), _translate("MainWindow", "Setup"))
        self.label_header_main_menu.setText(_translate("MainWindow", "Main Menu"))
        self.pushButton_98.setText(_translate("MainWindow", "Select"))
        self.label_98.setText(_translate("MainWindow", "Menu Background"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_main_menu), _translate("MainWindow", "Main Menu"))
        self.label_header_cursor.setText(_translate("MainWindow", "Cursor"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_cursor), _translate("MainWindow", "Cursor"))
        self.label_header_song_selection.setText(_translate("MainWindow", "Song Selection"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_song_selection), _translate("MainWindow", "Song Selection"))
        self.label_header_mod_selection.setText(_translate("MainWindow", "Mod Selection"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_mod_selection), _translate("MainWindow", "Mod Selection"))
        self.label_header_gamemode.setText(_translate("MainWindow", "Gamemode"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_gamemode), _translate("MainWindow", "Gamemode"))
        self.label_header_grade.setText(_translate("MainWindow", "Results Screen"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_grade), _translate("MainWindow", "Results Screen"))
        self.label_header_score_numbers.setText(_translate("MainWindow", "Score Numbers"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_score_numbers), _translate("MainWindow", "Score Number"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_UI), _translate("MainWindow", "UI Elements"))
        self.label_header_cursor_2.setText(_translate("MainWindow", "Pause Screen"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_pause_screen), _translate("MainWindow", "Pause Screen"))
        self.label_header_scorebar.setText(_translate("MainWindow", "Scorebar"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_scorebar), _translate("MainWindow", "Scorebar"))
        self.label_header_countdown.setText(_translate("MainWindow", "Countdown"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_countdown), _translate("MainWindow", "Countdown"))
        self.label_header_leaderboard.setText(_translate("MainWindow", "Leaderboard"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_leaderboard), _translate("MainWindow", "Leaderboard"))
        self.label_header_playfield.setText(_translate("MainWindow", "Playfield"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_playfield), _translate("MainWindow", "Playfield"))
        self.label_header_key_counter.setText(_translate("MainWindow", "Key Counter"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_key_counter), _translate("MainWindow", "Key Counter"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_gameplay), _translate("MainWindow", "Gameplay"))
        self.label_header_standard_hitcircle_numbers.setText(_translate("MainWindow", "Hitcircle Numbers"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_hitcircle_numbers), _translate("MainWindow", "Hitcircle Numbers"))
        self.label_header_standard_hitcircles.setText(_translate("MainWindow", "Hitcircles"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_hitcircle_object), _translate("MainWindow", "Hitcircles"))
        self.label_header_standard_slidertrack.setText(_translate("MainWindow", "Slidertrack"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_slidertrack), _translate("MainWindow", "Slidertrack"))
        self.label_header_standard_spinner.setText(_translate("MainWindow", "Spinner"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_spinner), _translate("MainWindow", "Spinner"))
        self.label_header_standard_hitbursts.setText(_translate("MainWindow", "Hitbursts"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_hitbursts), _translate("MainWindow", "Hitbursts"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_standard), _translate("MainWindow", "Standard"))
        self.tabWidget_7.setTabText(self.tabWidget_7.indexOf(self.tab_mania_stage), _translate("MainWindow", "Stage"))
        self.tabWidget_7.setTabText(self.tabWidget_7.indexOf(self.tab_mania_keys), _translate("MainWindow", "Keys"))
        self.tabWidget_7.setTabText(self.tabWidget_7.indexOf(self.tab_mania_notes), _translate("MainWindow", "Notes"))
        self.tabWidget_7.setTabText(self.tabWidget_7.indexOf(self.tab_mania_hitbursts), _translate("MainWindow", "Hitbursts"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_mania), _translate("MainWindow", "Mania"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_taiko_pippidon), _translate("MainWindow", "Pippidon"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_taiko_slider_bar), _translate("MainWindow", "Slider Bar"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_taiko_drum_bar), _translate("MainWindow", "Drum Bar"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_taiko_notes), _translate("MainWindow", "Notes"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_taiko_drumroll), _translate("MainWindow", "Drumroll"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_taiko_swell), _translate("MainWindow", "Swell"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_taiko_hitbursts), _translate("MainWindow", "Hitbursts"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_taiko), _translate("MainWindow", "Taiko"))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.tab_catch_catcher), _translate("MainWindow", "Catcher + Playfield"))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.tab_catch_fruits), _translate("MainWindow", "Fruits"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_catch), _translate("MainWindow", "Catch"))
        self.label_completion.setText(_translate("MainWindow", "Completion"))
        self.label_output_folder.setText(_translate("MainWindow", "Output Location"))
        self.pushButton_output_folder.setText(_translate("MainWindow", "Select"))
        self.pushButton_create_skin.setText(_translate("MainWindow", "Create Skin!"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_completion), _translate("MainWindow", "Completion"))
        self.actionNew_Skin.setText(_translate("MainWindow", "New Skin"))
        ##########################################
        """self.fields = {  "UI": {
                        "main_menu" : {
                            "Menu Background": {},
                            "Welcome" : {},
                            "Menu Snow": {},
                            "Options Offset Tick" : {}
                        },
                        "cursor" : {
                            "Cursor" : {},
                            "Cursor Trail" : {},
                            "Cursor Middle" : {},
                            "Cursor Smoke" : {},
                            "Cursor Ripple" : {}
                        },
                        "song_selection" : {},
                        "mod_selection" : {},
                        "gamemode" : {},
                        "grade" : {},
                        "score_numbers" : {}
                    },
                    "gameplay" : {
                        "pause_screen" : {},
                        "scorebar" : {},
                        "countdown" : {},
                        "leaderboard" : {},
                        "playfield" : {},
                        "key_counter" : {}
                    },
                    "standard" : {
                        "hitcircle_numbers" : {},
                        "slidertrack" : {},
                        "spinner" : {},
                        "hitbursts" : {}
                    },
                    "mania" : {
                        "mania_stage" : {},
                        "mania_keys" : {},
                        "mania_notes" : {},
                        "mania_hitbursts" : {}
                    },
                    "taiko" : {
                        "taiko_pippidon" : {},
                        "taiko_slider_bar" : {},
                        "taiko_drum_bar" : {},
                        "taiko_notes" : {},
                        "taiko_drumroll" : {},
                        "taiko_swell" : {},
                        "taiko_hitbursts" : {}
                    },
                    "catch" : {
                        "catch_catcher" : {},
                        "catch_fruits" : {}
                    }
                    }"""
        self.addUiText()


    def createFields(self):
        start_x = 40
        start_y = 60
        delta_x = 410
        delta_y = 40
        delta_lineEdit = 230
        delta_pushButton = 120
        for tab_a in self.fields:
            for tab_b in self.fields[tab_a]:
                i = 0
                for field in self.fields[tab_a][tab_b]:
                    row = int(i / 2)
                    col = i % 2
                    self.fields[tab_a][tab_b][field]["lineEdit"] = QtWidgets.QLineEdit(eval("self.tab_" + tab_b))
                    self.fields[tab_a][tab_b][field]["lineEdit"].setEnabled(True)
                    self.fields[tab_a][tab_b][field]["lineEdit"].setGeometry(QtCore.QRect(start_x + delta_x * col + delta_lineEdit, start_y + delta_y * row, 113, 20))
                    self.fields[tab_a][tab_b][field]["lineEdit"].setObjectName("lineEdit_" + field)
                    self.fields[tab_a][tab_b][field]["label"] = QtWidgets.QLabel(eval("self.tab_" + tab_b))
                    self.fields[tab_a][tab_b][field]["label"].setGeometry(QtCore.QRect(start_x + delta_x * col , start_y + delta_y * row, 111, 16))
                    self.fields[tab_a][tab_b][field]["label"].setObjectName("label_" + field)
                    self.fields[tab_a][tab_b][field]["pushButton"] = QtWidgets.QPushButton(eval("self.tab_" + tab_b))
                    self.fields[tab_a][tab_b][field]["pushButton"].setGeometry(QtCore.QRect(start_x + delta_x * col + delta_pushButton, start_y + delta_y * row, 75, 23))
                    self.fields[tab_a][tab_b][field]["pushButton"].setObjectName("pushButton_" + field)
                    i += 1

    def addUiText(self):
        for tab_a in self.fields:
            for tab_b in self.fields[tab_a]:
                for field in self.fields[tab_a][tab_b]:
                    self.fields[tab_a][tab_b][field]["label"].setText(field)
                    self.fields[tab_a][tab_b][field]["pushButton"].setText("Select")

    def add_element(self, lineEdit):
        print("AddElement")
        Dialog = QtWidgets.QDialog()
        ui = AddElement()
        ui.setupUi(Dialog)
        Dialog.show()
        Dialog.exec_()
        try:
            lineEdit.setText(ui.return_value)
        except:
            pass

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
